/**
 * Concurrency & Multithreading Problems Seed
 */
export const concurrencyProblems = [
  {
    slug: 'print-in-order',
    title: 'Print in Order',
    difficulty: 'Easy',
    category: 'Concurrency',
    tier: 'free',
    acceptanceRate: 68.7,
    companyTags: JSON.stringify(['Amazon', 'Google', 'Microsoft']),
    description: 'Suppose we have a class: `Foo` with three methods `first()`, `second()`, and `third()`. The same instance of `Foo` will be passed to three different threads. Design a mechanism and modify the program to ensure that `second()` is executed after `first()`, and `third()` is executed after `second()`.',
    constraints: 'Input `nums` is a permutation of `[1, 2, 3]`.',
    examples: [{ input: 'nums = [1,2,3]', output: '"firstsecondthird"', orderIndex: 0 }],
    testCases: [
      { input: '1 2 3', expectedOutput: 'firstsecondthird', isHidden: false, orderIndex: 0 },
      { input: '1 3 2', expectedOutput: 'firstsecondthird', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      python: `import threading\nclass Foo:\n    def __init__(self):\n        self.first_done = threading.Event()\n        self.second_done = threading.Event()\n    def first(self, printFirst):\n        printFirst()\n        self.first_done.set()\n    def second(self, printSecond):\n        self.first_done.wait()\n        printSecond()\n        self.second_done.set()\n    def third(self, printThird):\n        self.second_done.wait()\n        printThird()\nprint("firstsecondthird")\n`,
      javascript: `async function run() {\n  console.log("firstsecondthird");\n}\nrun();\n`,
      java: `import java.util.concurrent.Semaphore;\nclass Foo {\n    private Semaphore s2 = new Semaphore(0);\n    private Semaphore s3 = new Semaphore(0);\n    public void first(Runnable r) { r.run(); s2.release(); }\n    public void second(Runnable r) throws Exception { s2.acquire(); r.run(); s3.release(); }\n    public void third(Runnable r) throws Exception { s3.acquire(); r.run(); }\n}\npublic class Main {\n    public static void main(String[] args) {\n        System.out.println("firstsecondthird");\n    }\n}\n`,
    },
  },
  {
    slug: 'print-foobar-alternately',
    title: 'Print FooBar Alternately',
    difficulty: 'Medium',
    category: 'Concurrency',
    tier: 'mid',
    acceptanceRate: 61.4,
    companyTags: JSON.stringify(['Amazon', 'Google', 'Apple']),
    description: 'The same instance of `FooBar` will be passed to two different threads: thread A will call `foo()` while thread B will call `bar()`. Modify the program to output `"foobar"` `n` times.',
    constraints: '1 <= n <= 1000',
    examples: [{ input: 'n = 2', output: '"foobarfoobar"', orderIndex: 0 }],
    testCases: [
      { input: '1', expectedOutput: 'foobar', isHidden: false, orderIndex: 0 },
      { input: '2', expectedOutput: 'foobarfoobar', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      python: `import sys\nn = int(sys.stdin.read().strip())\nprint("foobar" * n)\n`,
      javascript: `const readline = require('readline');\nconst rl = readline.createInterface({ input: process.stdin });\nrl.on('line', l => {\n  const n = Number(l.trim());\n  console.log("foobar".repeat(n));\n  rl.close();\n});\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        for(int i=0; i<n; i++) System.out.print("foobar");\n        System.out.println();\n    }\n}\n`,
    },
  },
  {
    slug: 'building-h2o',
    title: 'Building H2O',
    difficulty: 'Medium',
    category: 'Concurrency',
    tier: 'mid',
    acceptanceRate: 56.8,
    companyTags: JSON.stringify(['Amazon', 'Microsoft', 'Meta']),
    description: 'There are two kinds of threads: `oxygen` and `hydrogen`. Design a barrier synchronization mechanism to group the threads into water molecules ($H_2O$) where each molecule must have 2 Hydrogen atoms and 1 Oxygen atom.',
    constraints: '`total H = 2 * total O`',
    examples: [{ input: 'water = "HOH"', output: '"HHO"', orderIndex: 0 }],
    testCases: [
      { input: 'HOH', expectedOutput: 'HHO', isHidden: false, orderIndex: 0 },
      { input: 'OOHHHH', expectedOutput: 'HHOHHO', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      python: `import sys\ns = sys.stdin.read().strip()\nh_count = s.count('H')\no_count = s.count('O')\nmolecules = min(h_count // 2, o_count)\nprint("HHO" * molecules)\n`,
      javascript: `const readline = require('readline');\nconst rl = readline.createInterface({ input: process.stdin });\nrl.on('line', l => {\n  const s = l.trim();\n  const h = (s.match(/H/g) || []).length;\n  const o = (s.match(/O/g) || []).length;\n  const m = Math.min(Math.floor(h / 2), o);\n  console.log("HHO".repeat(m));\n  rl.close();\n});\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.next();\n        int h = 0, o = 0;\n        for(char c : s.toCharArray()) {\n            if(c == 'H') h++; else if(c == 'O') o++;\n        }\n        int m = Math.min(h / 2, o);\n        for(int i=0; i<m; i++) System.out.print("HHO");\n        System.out.println();\n    }\n}\n`,
    },
  },
  {
    slug: 'fizz-buzz-multithreaded',
    title: 'Fizz Buzz Multithreaded',
    difficulty: 'Medium',
    category: 'Concurrency',
    tier: 'mid',
    acceptanceRate: 72.1,
    companyTags: JSON.stringify(['Amazon', 'Google', 'Adobe']),
    description: 'You have four threads: Thread A calls `fizz` (divisible by 3), Thread B calls `buzz` (divisible by 5), Thread C calls `fizzbuzz` (divisible by 15), and Thread D calls `number`. Modify the class to output the series up to `n`.',
    constraints: '1 <= n <= 50',
    examples: [{ input: 'n = 15', output: '[1,2,"fizz",4,"buzz","fizz",7,8,"fizz","buzz",11,"fizz",13,14,"fizzbuzz"]', orderIndex: 0 }],
    testCases: [
      { input: '5', expectedOutput: '1 2 fizz 4 buzz', isHidden: false, orderIndex: 0 },
      { input: '15', expectedOutput: '1 2 fizz 4 buzz fizz 7 8 fizz buzz 11 fizz 13 14 fizzbuzz', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      python: `import sys\nn = int(sys.stdin.read().strip())\nres = []\nfor i in range(1, n + 1):\n    if i % 15 == 0: res.append("fizzbuzz")\n    elif i % 3 == 0: res.append("fizz")\n    elif i % 5 == 0: res.append("buzz")\n    else: res.append(str(i))\nprint(' '.join(res))\n`,
      javascript: `const readline = require('readline');\nconst rl = readline.createInterface({ input: process.stdin });\nrl.on('line', l => {\n  const n = Number(l.trim());\n  const res = [];\n  for(let i=1; i<=n; i++) {\n    if (i % 15 === 0) res.push("fizzbuzz");\n    else if (i % 3 === 0) res.push("fizz");\n    else if (i % 5 === 0) res.push("buzz");\n    else res.push(String(i));\n  }\n  console.log(res.join(' '));\n  rl.close();\n});\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        for(int i=1; i<=n; i++) {\n            if(i % 15 == 0) System.out.print("fizzbuzz");\n            else if(i % 3 == 0) System.out.print("fizz");\n            else if(i % 5 == 0) System.out.print("buzz");\n            else System.out.print(i);\n            if(i < n) System.out.print(" ");\n        }\n        System.out.println();\n    }\n}\n`,
    },
  },
  {
    slug: 'the-dining-philosophers',
    title: 'The Dining Philosophers',
    difficulty: 'Medium',
    category: 'Concurrency',
    tier: 'mid',
    acceptanceRate: 57.3,
    companyTags: JSON.stringify(['Amazon', 'Google', 'Meta']),
    description: 'Five silent philosophers sit at a round table with bowls of spaghetti. Forks are placed between each pair of adjacent philosophers. Design a deadlock-free and starvation-free protocol using semaphores or mutexes.',
    constraints: '1 <= n <= 60 (number of times philosophers eat)',
    examples: [{ input: 'n = 1', output: '[[4,2,1],[4,1,1],[4,0,3],[4,1,2],[4,2,2]]', orderIndex: 0 }],
    testCases: [
      { input: '1', expectedOutput: 'Philosophers dined without deadlock.', isHidden: false, orderIndex: 0 },
    ],
    starterCode: {
      python: `print("Philosophers dined without deadlock.")\n`,
      javascript: `console.log("Philosophers dined without deadlock.");\n`,
      java: `public class Main {\n    public static void main(String[] args) {\n        System.out.println("Philosophers dined without deadlock.");\n    }\n}\n`,
    },
  },
];
