/**
 * Database & SQL Problems Seed
 */
export const databaseProblems = [
  {
    slug: 'combine-two-tables',
    title: 'Combine Two Tables',
    difficulty: 'Easy',
    category: 'Database',
    tier: 'free',
    acceptanceRate: 74.5,
    companyTags: JSON.stringify(['Amazon', 'Apple', 'Google', 'Microsoft']),
    description: 'Write a solution to report the `firstName`, `lastName`, `city`, and `state` of each person in the `Person` table. If the address of a `personId` is not present in the `Address` table, report `null` instead.',
    constraints: 'Return the result table in any order.',
    examples: [{ input: 'Person = [[1, "Wang", "Allen"]], Address = [[1, 2, "New York City", "New York"]]', output: '[["Allen", "Wang", null, null]]', orderIndex: 0 }],
    testCases: [
      { input: '1', expectedOutput: 'Allen Wang null null', isHidden: false, orderIndex: 0 },
      { input: '2', expectedOutput: 'Bob Alice Seattle Washington', isHidden: false, orderIndex: 1 },
      { input: '3', expectedOutput: 'Carol Dan Austin Texas', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\n# SQL Solution simulation in Python\nprint("firstName lastName city state")\n`,
      javascript: `// SQL Query representation\nconsole.log("SELECT p.firstName, p.lastName, a.city, a.state FROM Person p LEFT JOIN Address a ON p.personId = a.personId;");\n`,
      java: `public class Main {\n    public static void main(String[] args) {\n        System.out.println("SELECT p.firstName, p.lastName, a.city, a.state FROM Person p LEFT JOIN Address a ON p.personId = a.personId;");\n    }\n}\n`,
    },
  },
  {
    slug: 'second-highest-salary',
    title: 'Second Highest Salary',
    difficulty: 'Medium',
    category: 'Database',
    tier: 'mid',
    acceptanceRate: 41.2,
    companyTags: JSON.stringify(['Amazon', 'Google', 'Microsoft', 'Adobe']),
    description: 'Write a solution to find the second highest distinct salary from the `Employee` table. If there is no second highest salary, return `null` (or `None` in Python).',
    constraints: 'The `Employee` table contains `id` and `salary`.',
    examples: [{ input: 'Employee = [[1, 100], [2, 200], [3, 300]]', output: '200', orderIndex: 0 }],
    testCases: [
      { input: '100 200 300', expectedOutput: '200', isHidden: false, orderIndex: 0 },
      { input: '100', expectedOutput: 'null', isHidden: false, orderIndex: 1 },
      { input: '500 500 500', expectedOutput: 'null', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nsalaries = list(set(map(int, sys.stdin.read().strip().split())))\nsalaries.sort(reverse=True)\nprint(salaries[1] if len(salaries) > 1 else 'null')\n`,
      javascript: `const readline = require('readline');\nconst rl = readline.createInterface({ input: process.stdin });\nrl.on('line', l => {\n  const s = Array.from(new Set(l.trim().split(/\\s+/).map(Number))).sort((a,b) => b-a);\n  console.log(s.length > 1 ? s[1] : 'null');\n  rl.close();\n});\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        TreeSet<Integer> set = new TreeSet<>();\n        while(sc.hasNextInt()) set.add(sc.nextInt());\n        if(set.size() < 2) System.out.println("null");\n        else {\n            set.pollLast();\n            System.out.println(set.last());\n        }\n    }\n}\n`,
    },
  },
  {
    slug: 'nth-highest-salary',
    title: 'Nth Highest Salary',
    difficulty: 'Medium',
    category: 'Database',
    tier: 'mid',
    acceptanceRate: 38.6,
    companyTags: JSON.stringify(['Amazon', 'Google', 'Meta']),
    description: 'Write a solution to find the `nth` highest salary from the `Employee` table. If there are fewer than `n` distinct salaries, return `null`.',
    constraints: '`n >= 1`',
    examples: [{ input: 'n = 2, Employee = [[1, 100], [2, 200], [3, 300]]', output: '200', orderIndex: 0 }],
    testCases: [
      { input: '2\n100 200 300', expectedOutput: '200', isHidden: false, orderIndex: 0 },
      { input: '3\n100 200', expectedOutput: 'null', isHidden: false, orderIndex: 1 },
      { input: '1\n500', expectedOutput: '500', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nlines = sys.stdin.read().strip().split('\\n')\nn = int(lines[0])\nsalaries = list(set(map(int, lines[1].split())))\nsalaries.sort(reverse=True)\nprint(salaries[n-1] if len(salaries) >= n else 'null')\n`,
      javascript: `const fs = require('fs');\nconst lines = fs.readFileSync(0, 'utf-8').trim().split('\\n');\nconst n = Number(lines[0]);\nconst s = Array.from(new Set(lines[1].trim().split(/\\s+/).map(Number))).sort((a,b) => b-a);\nconsole.log(s.length >= n ? s[n-1] : 'null');\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        TreeSet<Integer> set = new TreeSet<>();\n        while(sc.hasNextInt()) set.add(sc.nextInt());\n        List<Integer> list = new ArrayList<>(set);\n        Collections.reverse(list);\n        if(list.size() >= n) System.out.println(list.get(n-1));\n        else System.out.println("null");\n    }\n}\n`,
    },
  },
  {
    slug: 'customers-who-never-order',
    title: 'Customers Who Never Order',
    difficulty: 'Easy',
    category: 'Database',
    tier: 'free',
    acceptanceRate: 68.9,
    companyTags: JSON.stringify(['Amazon', 'Apple']),
    description: 'Find all customers who never order anything. Return the customer names table with column name `Customers`.',
    constraints: 'Tables: `Customers (id, name)` and `Orders (id, customerId)`.',
    examples: [{ input: 'Customers = [[1, "Joe"], [2, "Henry"], [3, "Sam"], [4, "Max"]], Orders = [[1, 3], [2, 1]]', output: 'Henry\nMax', orderIndex: 0 }],
    testCases: [
      { input: 'Joe Henry Sam Max\nSam Joe', expectedOutput: 'Henry\nMax', isHidden: false, orderIndex: 0 },
      { input: 'Alice Bob\nAlice Bob', expectedOutput: 'None', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      python: `import sys\nlines = sys.stdin.read().strip().split('\\n')\nall_cust = lines[0].split()\nordered = set(lines[1].split()) if len(lines) > 1 else set()\nnever = [c for c in all_cust if c not in ordered]\nprint('\\n'.join(never) if never else 'None')\n`,
      javascript: `const fs = require('fs');\nconst [l1, l2] = fs.readFileSync(0, 'utf-8').trim().split('\\n');\nconst allCust = l1.split(/\\s+/);\nconst ord = new Set(l2 ? l2.split(/\\s+/) : []);\nconst never = allCust.filter(c => !ord.has(c));\nconsole.log(never.length ? never.join('\\n') : 'None');\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String[] all = sc.nextLine().split(" ");\n        Set<String> ord = new HashSet<>();\n        if(sc.hasNextLine()) for(String s : sc.nextLine().split(" ")) ord.add(s);\n        boolean found = false;\n        for(String s : all) {\n            if(!ord.contains(s)) { System.out.println(s); found = true; }\n        }\n        if(!found) System.out.println("None");\n    }\n}\n`,
    },
  },
  {
    slug: 'duplicate-emails',
    title: 'Duplicate Emails',
    difficulty: 'Easy',
    category: 'Database',
    tier: 'free',
    acceptanceRate: 71.4,
    companyTags: JSON.stringify(['Amazon', 'Google', 'Microsoft']),
    description: 'Write a solution to report all the duplicate emails. Note that it is guaranteed that the email field is not NULL.',
    constraints: 'Return the email list in any order.',
    examples: [{ input: 'Person = [[1, "a@b.com"], [2, "c@d.com"], [3, "a@b.com"]]', output: 'a@b.com', orderIndex: 0 }],
    testCases: [
      { input: 'a@b.com c@d.com a@b.com', expectedOutput: 'a@b.com', isHidden: false, orderIndex: 0 },
      { input: 'x@y.com z@w.com', expectedOutput: 'None', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      python: `import sys\nfrom collections import Counter\nemails = sys.stdin.read().strip().split()\ncounts = Counter(emails)\ndupes = [e for e, c in counts.items() if c > 1]\nprint('\\n'.join(dupes) if dupes else 'None')\n`,
      javascript: `const fs = require('fs');\nconst emails = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/);\nconst counts = {};\nemails.forEach(e => counts[e] = (counts[e] || 0) + 1);\nconst dupes = Object.keys(counts).filter(e => counts[e] > 1);\nconsole.log(dupes.length ? dupes.join('\\n') : 'None');\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        Map<String, Integer> map = new HashMap<>();\n        while(sc.hasNext()) {\n            String s = sc.next();\n            map.put(s, map.getOrDefault(s, 0) + 1);\n        }\n        boolean found = false;\n        for(var e : map.entrySet()) {\n            if(e.getValue() > 1) { System.out.println(e.getKey()); found = true; }\n        }\n        if(!found) System.out.println("None");\n    }\n}\n`,
    },
  },
  {
    slug: 'rising-temperature',
    title: 'Rising Temperature',
    difficulty: 'Easy',
    category: 'Database',
    tier: 'free',
    acceptanceRate: 53.2,
    companyTags: JSON.stringify(['Amazon', 'Google', 'Adobe']),
    description: 'Write a solution to find all dates IDs with higher temperatures compared to its previous dates (yesterday).',
    constraints: 'Dates are consecutive calendar days.',
    examples: [{ input: 'Weather = [[1, "2015-01-01", 10], [2, "2015-01-02", 25], [3, "2015-01-03", 20], [4, "2015-01-04", 30]]', output: '2\n4', orderIndex: 0 }],
    testCases: [
      { input: '10 25 20 30', expectedOutput: '2\n4', isHidden: false, orderIndex: 0 },
      { input: '30 20 10', expectedOutput: 'None', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      python: `import sys\ntemps = list(map(int, sys.stdin.read().strip().split()))\nans = [str(i + 1) for i in range(1, len(temps)) if temps[i] > temps[i - 1]]\nprint('\\n'.join(ans) if ans else 'None')\n`,
      javascript: `const fs = require('fs');\nconst t = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/).map(Number);\nconst res = [];\nfor (let i = 1; i < t.length; i++) {\n  if (t[i] > t[i-1]) res.push(i + 1);\n}\nconsole.log(res.length ? res.join('\\n') : 'None');\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        List<Integer> t = new ArrayList<>();\n        while(sc.hasNextInt()) t.add(sc.nextInt());\n        List<Integer> res = new ArrayList<>();\n        for(int i = 1; i < t.size(); i++) {\n            if(t.get(i) > t.get(i-1)) res.add(i+1);\n        }\n        if(res.isEmpty()) System.out.println("None");\n        else for(int x : res) System.out.println(x);\n    }\n}\n`,
    },
  },
  {
    slug: 'department-highest-salary',
    title: 'Department Highest Salary',
    difficulty: 'Medium',
    category: 'Database',
    tier: 'mid',
    acceptanceRate: 51.0,
    companyTags: JSON.stringify(['Amazon', 'Google', 'Microsoft']),
    description: 'Find employees who have the highest salary in each of the departments.',
    constraints: 'Return department name, employee name, and salary.',
    examples: [{ input: 'IT: [Max 90000, Joe 85000], Sales: [Henry 80000, Sam 60000]', output: 'IT Max 90000\nSales Henry 80000', orderIndex: 0 }],
    testCases: [
      { input: 'IT Max 90000\nIT Joe 85000\nSales Henry 80000', expectedOutput: 'IT Max 90000\nSales Henry 80000', isHidden: false, orderIndex: 0 },
    ],
    starterCode: {
      python: `import sys\nlines = sys.stdin.read().strip().split('\\n')\ndepts = {}\nfor l in lines:\n    if not l.strip(): continue\n    d, name, sal = l.split()\n    sal = int(sal)\n    if d not in depts or sal > depts[d][1]:\n        depts[d] = (name, sal)\nfor d, (name, sal) in depts.items():\n    print(f"{d} {name} {sal}")\n`,
      javascript: `const fs = require('fs');\nconst lines = fs.readFileSync(0, 'utf-8').trim().split('\\n');\nconst depts = {};\nlines.forEach(l => {\n  if (!l.trim()) return;\n  const [d, name, sal] = l.split(/\\s+/);\n  const s = Number(sal);\n  if (!depts[d] || s > depts[d].sal) depts[d] = { name, sal: s };\n});\nObject.keys(depts).forEach(d => console.log(\`\${d} \${depts[d].name} \${depts[d].sal}\`));\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        Map<String, String> bestName = new LinkedHashMap<>();\n        Map<String, Integer> bestSal = new LinkedHashMap<>();\n        while(sc.hasNext()) {\n            String d = sc.next();\n            String name = sc.next();\n            int sal = sc.nextInt();\n            if(!bestSal.containsKey(d) || sal > bestSal.get(d)) {\n                bestSal.put(d, sal);\n                bestName.put(d, name);\n            }\n        }\n        for(String d : bestSal.keySet()) {\n            System.out.println(d + " " + bestName.get(d) + " " + bestSal.get(d));\n        }\n    }\n}\n`,
    },
  },
];
