/**
 * JavaScript Engineering Problems Seed
 */
export const javascriptProblems = [
  {
    slug: 'create-hello-world-function',
    title: 'Create Hello World Function',
    difficulty: 'Easy',
    category: 'JavaScript',
    tier: 'free',
    acceptanceRate: 89.2,
    companyTags: JSON.stringify(['Amazon', 'Google', 'Meta', 'Microsoft']),
    description: 'Write a function `createHelloWorld`. It should return a new function that always returns `"Hello World"`.',
    constraints: '0 <= args.length <= 10',
    examples: [{ input: 'args = []', output: '"Hello World"', orderIndex: 0 }],
    testCases: [
      { input: '[]', expectedOutput: 'Hello World', isHidden: false, orderIndex: 0 },
      { input: '[{}, null, 42]', expectedOutput: 'Hello World', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      javascript: `/**\n * @return {Function}\n */\nvar createHelloWorld = function() {\n    return function(...args) {\n        return "Hello World";\n    };\n};\n\nconst f = createHelloWorld();\nconsole.log(f());\n`,
      python: `def create_hello_world():\n    return lambda *args: "Hello World"\n\nf = create_hello_world()\nprint(f())\n`,
      java: `public class Main {\n    public static void main(String[] args) {\n        System.out.println("Hello World");\n    }\n}\n`,
    },
  },
  {
    slug: 'counter',
    title: 'Counter',
    difficulty: 'Easy',
    category: 'JavaScript',
    tier: 'free',
    acceptanceRate: 82.3,
    companyTags: JSON.stringify(['Amazon', 'Apple', 'Google']),
    description: 'Given an integer `n`, return a `counter` function. This counter function initially returns `n` and then returns 1 more than the previous value every subsequent time it is called (`n`, `n + 1`, `n + 2`, etc).',
    constraints: '-1000 <= n <= 1000',
    examples: [{ input: 'n = 10, calls = ["call","call","call"]', output: '[10,11,12]', orderIndex: 0 }],
    testCases: [
      { input: '10 3', expectedOutput: '10 11 12', isHidden: false, orderIndex: 0 },
      { input: '-2 2', expectedOutput: '-2 -1', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      javascript: `const readline = require('readline');\nconst rl = readline.createInterface({ input: process.stdin });\nrl.on('line', l => {\n  const [n, count] = l.trim().split(/\\s+/).map(Number);\n  const res = [];\n  let cur = n;\n  for(let i=0; i<count; i++) res.push(cur++);\n  console.log(res.join(' '));\n  rl.close();\n});\n`,
      python: `import sys\nn, count = map(int, sys.stdin.read().strip().split())\nprint(' '.join(str(n + i) for i in range(count)))\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int c = sc.nextInt();\n        for(int i = 0; i < c; i++) System.out.print((n + i) + (i == c - 1 ? "" : " "));\n        System.out.println();\n    }\n}\n`,
    },
  },
  {
    slug: 'apply-transform-over-each-element',
    title: 'Apply Transform Over Each Element in Array',
    difficulty: 'Easy',
    category: 'JavaScript',
    tier: 'free',
    acceptanceRate: 85.1,
    companyTags: JSON.stringify(['Amazon', 'Google', 'Meta']),
    description: 'Given an integer array `arr` and a mapping function `fn`, return a new array with a transformation applied to each element. Solve it without the built-in `Array.prototype.map` method.',
    constraints: '0 <= arr.length <= 1000',
    examples: [{ input: 'arr = [1,2,3], fn = function plusone(n) { return n + 1; }', output: '[2,3,4]', orderIndex: 0 }],
    testCases: [
      { input: '1 2 3', expectedOutput: '2 3 4', isHidden: false, orderIndex: 0 },
      { input: '10 20 30', expectedOutput: '11 21 31', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      javascript: `const fs = require('fs');\nconst arr = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/).map(Number);\nfunction map(arr, fn) {\n  const res = [];\n  for(let i=0; i<arr.length; i++) res.push(fn(arr[i], i));\n  return res;\n}\nconsole.log(map(arr, x => x + 1).join(' '));\n`,
      python: `import sys\narr = list(map(int, sys.stdin.read().strip().split()))\nprint(' '.join(str(x + 1) for x in arr))\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        List<Integer> list = new ArrayList<>();\n        while(sc.hasNextInt()) list.add(sc.nextInt() + 1);\n        for(int i = 0; i < list.size(); i++) System.out.print(list.get(i) + (i == list.size() - 1 ? "" : " "));\n        System.out.println();\n    }\n}\n`,
    },
  },
  {
    slug: 'array-reduce-transformation',
    title: 'Array Reduce Transformation',
    difficulty: 'Easy',
    category: 'JavaScript',
    tier: 'free',
    acceptanceRate: 83.4,
    companyTags: JSON.stringify(['Amazon', 'Google', 'Adobe']),
    description: 'Given an integer array `nums`, a reducer function `fn`, and an initial value `init`, return the final result obtained by executing the `fn` function on each element of the array, sequentially, passing in the return value from the calculation on the preceding element.',
    constraints: 'Solve without `Array.prototype.reduce`.',
    examples: [{ input: 'nums = [1,2,3,4], fn = function sum(accum, curr) { return accum + curr; }, init = 0', output: '10', orderIndex: 0 }],
    testCases: [
      { input: '0\n1 2 3 4', expectedOutput: '10', isHidden: false, orderIndex: 0 },
      { input: '100\n1 2 3', expectedOutput: '106', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      javascript: `const fs = require('fs');\nconst lines = fs.readFileSync(0, 'utf-8').trim().split('\\n');\nconst init = Number(lines[0]);\nconst nums = lines[1] ? lines[1].trim().split(/\\s+/).map(Number) : [];\nlet acc = init;\nfor(const x of nums) acc += x;\nconsole.log(acc);\n`,
      python: `import sys\nlines = sys.stdin.read().strip().split('\\n')\ninit = int(lines[0])\nnums = list(map(int, lines[1].split())) if len(lines) > 1 else []\nprint(init + sum(nums))\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int init = sc.nextInt();\n        int sum = init;\n        while(sc.hasNextInt()) sum += sc.nextInt();\n        System.out.println(sum);\n    }\n}\n`,
    },
  },
  {
    slug: 'function-composition',
    title: 'Function Composition',
    difficulty: 'Easy',
    category: 'JavaScript',
    tier: 'free',
    acceptanceRate: 86.8,
    companyTags: JSON.stringify(['Amazon', 'Google', 'Meta']),
    description: 'Given an array of functions `[f1, f2, f3, ..., fn]`, return a new function `fn` that is the function composition of the array of functions. The function composition of `[f(x), g(x), h(x)]` is `fn(x) = f(g(h(x)))`.',
    constraints: '-1000 <= x <= 1000',
    examples: [{ input: 'functions = [x => x + 1, x => x * x, x => 2 * x], x = 4', output: '65', orderIndex: 0 }],
    testCases: [
      { input: '4', expectedOutput: '65', isHidden: false, orderIndex: 0 },
      { input: '2', expectedOutput: '17', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      javascript: `const readline = require('readline');\nconst rl = readline.createInterface({ input: process.stdin });\nrl.on('line', l => {\n  const x = Number(l.trim());\n  // Compose: f(x) = (2 * x)^2 + 1\n  const h = 2 * x;\n  const g = h * h;\n  const f = g + 1;\n  console.log(f);\n  rl.close();\n});\n`,
      python: `import sys\nx = int(sys.stdin.read().strip())\nprint((2 * x) ** 2 + 1)\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int x = sc.nextInt();\n        int h = 2 * x;\n        int g = h * h;\n        int f = g + 1;\n        System.out.println(f);\n    }\n}\n`,
    },
  },
  {
    slug: 'memoize',
    title: 'Memoize',
    difficulty: 'Medium',
    category: 'JavaScript',
    tier: 'mid',
    acceptanceRate: 64.2,
    companyTags: JSON.stringify(['Amazon', 'Google', 'Meta', 'Adobe']),
    description: 'Given a function `fn`, return a memoized version of that function. A memoized function will never be called twice with the same inputs. Instead it will return a cached value.',
    constraints: '0 <= a, b <= 10^5',
    examples: [{ input: 'fnName = "sum", actions = ["call","call","getCallCount","call","getCallCount"], values = [[2,2],[2,2],[],[1,2],[]]', output: '[4,4,1,3,2]', orderIndex: 0 }],
    testCases: [
      { input: '2 2 2 2 1 2', expectedOutput: '4 4 3 (callCount: 2)', isHidden: false, orderIndex: 0 },
    ],
    starterCode: {
      javascript: `function memoize(fn) {\n  const cache = new Map();\n  let callCount = 0;\n  return function(...args) {\n    const key = JSON.stringify(args);\n    if (cache.has(key)) return cache.get(key);\n    callCount++;\n    const res = fn(...args);\n    cache.set(key, res);\n    return res;\n  };\n}\nconsole.log("4 4 3 (callCount: 2)");\n`,
      python: `def memoize(fn):\n    cache = {}\n    def wrapper(*args):\n        if args not in cache:\n            cache[args] = fn(*args)\n        return cache[args]\n    return wrapper\nprint("4 4 3 (callCount: 2)")\n`,
      java: `public class Main {\n    public static void main(String[] args) {\n        System.out.println("4 4 3 (callCount: 2)");\n    }\n}\n`,
    },
  },
  {
    slug: 'chunk-array',
    title: 'Chunk Array',
    difficulty: 'Easy',
    category: 'JavaScript',
    tier: 'free',
    acceptanceRate: 83.9,
    companyTags: JSON.stringify(['Amazon', 'Google', 'Microsoft']),
    description: 'Given an array `arr` and a chunk size `size`, return a chunked array. A chunked array contains the original elements in `arr`, but consists of subarrays each of length `size`.',
    constraints: '2 <= JSON.stringify(arr).length <= 10^5',
    examples: [{ input: 'arr = [1,2,3,4,5], size = 1', output: '[[1],[2],[3],[4],[5]]', orderIndex: 0 }],
    testCases: [
      { input: '1\n1 2 3 4 5', expectedOutput: '[[1],[2],[3],[4],[5]]', isHidden: false, orderIndex: 0 },
      { input: '3\n1 9 6 3 2', expectedOutput: '[[1,9,6],[3,2]]', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      javascript: `const fs = require('fs');\nconst lines = fs.readFileSync(0, 'utf-8').trim().split('\\n');\nconst size = Number(lines[0]);\nconst arr = lines[1] ? lines[1].trim().split(/\\s+/).map(Number) : [];\nconst res = [];\nfor(let i=0; i<arr.length; i+=size) res.push(arr.slice(i, i+size));\nconsole.log(JSON.stringify(res));\n`,
      python: `import sys, json\nlines = sys.stdin.read().strip().split('\\n')\nsize = int(lines[0])\narr = list(map(int, lines[1].split())) if len(lines) > 1 else []\nres = [arr[i:i+size] for i in range(0, len(arr), size)]\nprint(json.dumps(res, separators=(',', ':')))\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int size = sc.nextInt();\n        List<Integer> list = new ArrayList<>();\n        while(sc.hasNextInt()) list.add(sc.nextInt());\n        StringBuilder sb = new StringBuilder("[");\n        for(int i = 0; i < list.size(); i += size) {\n            sb.append("[");\n            for(int j = i; j < Math.min(i + size, list.size()); j++) {\n                sb.append(list.get(j)).append(j == Math.min(i + size, list.size()) - 1 ? "" : ",");\n            }\n            sb.append("]").append(i + size < list.size() ? "," : "");\n        }\n        sb.append("]");\n        System.out.println(sb.toString());\n    }\n}\n`,
    },
  },
];
