/**
 * Step 4: Binary Search — Easy / Medium / Hard
 * Tier: Easy → 'free' | Medium → 'mid' | Hard → 'pro'
 */
export const step4Problems = [
  // ── EASY ────────────────────────────────────────────────────────────────────
  {
    slug: 'binary-search-classic',
    title: 'Binary Search',
    difficulty: 'Easy',
    category: 'Binary Search',
    tier: 'free',
    acceptanceRate: 83.0,
    description: 'Given a sorted array `nums` and a target integer, return the index of target or -1 if not found. Input: first line is the array, second line is the target.',
    constraints: '- `1 <= nums.length <= 10^4`\n- All elements unique, sorted ascending\n- `-10^4 <= nums[i], target <= 10^4`',
    examples: [{ input: '-1 0 3 5 9 12\n9', output: '4', orderIndex: 0 }],
    testCases: [
      { input: '-1 0 3 5 9 12\n9', expectedOutput: '4', isHidden: false, orderIndex: 0 },
      { input: '-1 0 3 5 9 12\n2', expectedOutput: '-1', isHidden: false, orderIndex: 1 },
      { input: '5\n5', expectedOutput: '0', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nlines = sys.stdin.read().split('\\n')\nnums = list(map(int, lines[0].split()))\ntarget = int(lines[1])\nlo, hi = 0, len(nums)-1\nwhile lo <= hi:\n    mid = (lo+hi)//2\n    if nums[mid] == target: print(mid); exit()\n    elif nums[mid] < target: lo = mid+1\n    else: hi = mid-1\nprint(-1)\n`,
      javascript: `const lines = require('fs').readFileSync('/dev/stdin','utf8').split('\\n');\nconst nums = lines[0].split(' ').map(Number);\nconst target = Number(lines[1]);\nlet lo = 0, hi = nums.length-1;\nwhile (lo <= hi) {\n  const mid = (lo+hi)>>1;\n  if (nums[mid] === target) { console.log(mid); process.exit(); }\n  else if (nums[mid] < target) lo = mid+1;\n  else hi = mid-1;\n}\nconsole.log(-1);\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int[] nums = Arrays.stream(sc.nextLine().split(\" \")).mapToInt(Integer::parseInt).toArray();\n        int target = sc.nextInt(), lo = 0, hi = nums.length-1;\n        while (lo <= hi) {\n            int mid = (lo+hi)/2;\n            if (nums[mid] == target) { System.out.println(mid); return; }\n            else if (nums[mid] < target) lo = mid+1;\n            else hi = mid-1;\n        }\n        System.out.println(-1);\n    }\n}\n`,
    },
  },
  {
    slug: 'lower-bound-search',
    title: 'Lower Bound in Sorted Array',
    difficulty: 'Easy',
    category: 'Binary Search',
    tier: 'free',
    acceptanceRate: 78.4,
    description: 'Given a sorted array `nums` and a target, return the index of the first element >= target (lower bound). If all elements are less, return `nums.length`.',
    constraints: '- `1 <= nums.length <= 10^5`\n- `-10^9 <= nums[i], target <= 10^9`',
    examples: [{ input: '1 3 5 7 9\n6', output: '3', orderIndex: 0 }],
    testCases: [
      { input: '1 3 5 7 9\n6', expectedOutput: '3', isHidden: false, orderIndex: 0 },
      { input: '1 3 5 7\n8', expectedOutput: '4', isHidden: false, orderIndex: 1 },
      { input: '2 4 6\n2', expectedOutput: '0', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys, bisect\nlines = sys.stdin.read().split('\\n')\nnums = list(map(int, lines[0].split()))\ntarget = int(lines[1])\nprint(bisect.bisect_left(nums, target))\n`,
      javascript: `const lines = require('fs').readFileSync('/dev/stdin','utf8').split('\\n');\nconst nums = lines[0].split(' ').map(Number);\nconst target = Number(lines[1]);\nlet lo = 0, hi = nums.length;\nwhile (lo < hi) { const mid = (lo+hi)>>1; if (nums[mid] < target) lo = mid+1; else hi = mid; }\nconsole.log(lo);\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int[] nums = Arrays.stream(sc.nextLine().split(\" \")).mapToInt(Integer::parseInt).toArray();\n        int target = sc.nextInt(), lo = 0, hi = nums.length;\n        while (lo < hi) { int mid = (lo+hi)/2; if (nums[mid] < target) lo = mid+1; else hi = mid; }\n        System.out.println(lo);\n    }\n}\n`,
    },
  },
  {
    slug: 'search-insert-position',
    title: 'Search Insert Position',
    difficulty: 'Easy',
    category: 'Binary Search',
    tier: 'free',
    acceptanceRate: 80.5,
    description: 'Given a sorted array with unique values and a target, return the index where the target is found, or the index where it would be inserted to keep the array sorted.',
    constraints: '- `1 <= nums.length <= 10^4`\n- Distinct values, sorted ascending\n- `-10^4 <= nums[i], target <= 10^4`',
    examples: [{ input: '1 3 5 6\n5', output: '2', orderIndex: 0 }],
    testCases: [
      { input: '1 3 5 6\n5', expectedOutput: '2', isHidden: false, orderIndex: 0 },
      { input: '1 3 5 6\n2', expectedOutput: '1', isHidden: false, orderIndex: 1 },
      { input: '1 3 5 6\n7', expectedOutput: '4', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys, bisect\nlines = sys.stdin.read().split('\\n')\nnums = list(map(int, lines[0].split()))\ntarget = int(lines[1])\nprint(bisect.bisect_left(nums, target))\n`,
      javascript: `const lines = require('fs').readFileSync('/dev/stdin','utf8').split('\\n');\nconst nums = lines[0].split(' ').map(Number);\nconst t = Number(lines[1]);\nlet lo = 0, hi = nums.length;\nwhile (lo < hi) { const mid = (lo+hi)>>1; if (nums[mid] < t) lo = mid+1; else hi = mid; }\nconsole.log(lo);\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int[] nums = Arrays.stream(sc.nextLine().split(\" \")).mapToInt(Integer::parseInt).toArray();\n        int t = sc.nextInt(), lo = 0, hi = nums.length;\n        while (lo < hi) { int mid = (lo+hi)/2; if (nums[mid] < t) lo = mid+1; else hi = mid; }\n        System.out.println(lo);\n    }\n}\n`,
    },
  },
  // ── MEDIUM ────────────────────────────────────────────────────────────────────
  {
    slug: 'search-rotated-sorted',
    title: 'Search in Rotated Sorted Array',
    difficulty: 'Medium',
    category: 'Binary Search',
    tier: 'mid',
    acceptanceRate: 61.5,
    description: 'An array sorted in ascending order was rotated at an unknown pivot. Given the rotated array and a target, return the target\'s index or -1.',
    constraints: '- `1 <= nums.length <= 5000`\n- All values unique\n- `-10^4 <= nums[i], target <= 10^4`',
    examples: [{ input: '4 5 6 7 0 1 2\n0', output: '4', orderIndex: 0 }],
    testCases: [
      { input: '4 5 6 7 0 1 2\n0', expectedOutput: '4', isHidden: false, orderIndex: 0 },
      { input: '4 5 6 7 0 1 2\n3', expectedOutput: '-1', isHidden: false, orderIndex: 1 },
      { input: '1\n0', expectedOutput: '-1', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nlines = sys.stdin.read().split('\\n')\nnums = list(map(int, lines[0].split()))\ntarget = int(lines[1])\nlo, hi = 0, len(nums)-1\nwhile lo <= hi:\n    mid = (lo+hi)//2\n    if nums[mid] == target: print(mid); exit()\n    if nums[lo] <= nums[mid]:\n        if nums[lo] <= target < nums[mid]: hi = mid-1\n        else: lo = mid+1\n    else:\n        if nums[mid] < target <= nums[hi]: lo = mid+1\n        else: hi = mid-1\nprint(-1)\n`,
      javascript: `const lines = require('fs').readFileSync('/dev/stdin','utf8').split('\\n');\nconst nums = lines[0].split(' ').map(Number);\nconst target = Number(lines[1]);\nlet lo = 0, hi = nums.length-1;\nwhile (lo <= hi) {\n  const mid = (lo+hi)>>1;\n  if (nums[mid] === target) { console.log(mid); process.exit(); }\n  if (nums[lo] <= nums[mid]) {\n    if (nums[lo] <= target && target < nums[mid]) hi = mid-1; else lo = mid+1;\n  } else {\n    if (nums[mid] < target && target <= nums[hi]) lo = mid+1; else hi = mid-1;\n  }\n}\nconsole.log(-1);\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int[] nums = Arrays.stream(sc.nextLine().split(\" \")).mapToInt(Integer::parseInt).toArray();\n        int target = sc.nextInt(), lo = 0, hi = nums.length-1;\n        while (lo <= hi) {\n            int mid = (lo+hi)/2;\n            if (nums[mid] == target) { System.out.println(mid); return; }\n            if (nums[lo] <= nums[mid]) {\n                if (nums[lo] <= target && target < nums[mid]) hi = mid-1; else lo = mid+1;\n            } else {\n                if (nums[mid] < target && target <= nums[hi]) lo = mid+1; else hi = mid-1;\n            }\n        }\n        System.out.println(-1);\n    }\n}\n`,
    },
  },
  {
    slug: 'find-peak-element',
    title: 'Find Peak Element',
    difficulty: 'Medium',
    category: 'Binary Search',
    tier: 'mid',
    acceptanceRate: 58.9,
    description: 'A peak element is one that is strictly greater than its neighbors. Given an array `nums`, find any peak element index using O(log n) time. Assume `nums[-1] = nums[n] = -∞`.',
    constraints: '- `1 <= nums.length <= 1000`\n- `-2^31 <= nums[i] <= 2^31 - 1`\n- All adjacent elements are distinct',
    examples: [{ input: '1 2 3 1', output: '2', orderIndex: 0 }],
    testCases: [
      { input: '1 2 3 1', expectedOutput: '2', isHidden: false, orderIndex: 0 },
      { input: '1 2 1 3 5 6 4', expectedOutput: '5', isHidden: false, orderIndex: 1 },
      { input: '1', expectedOutput: '0', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nnums = list(map(int, sys.stdin.read().split()))\nlo, hi = 0, len(nums)-1\nwhile lo < hi:\n    mid = (lo+hi)//2\n    if nums[mid] > nums[mid+1]: hi = mid\n    else: lo = mid+1\nprint(lo)\n`,
      javascript: `const rl = require('readline').createInterface({ input: process.stdin });\nrl.on('line', l => {\n  const a = l.split(' ').map(Number);\n  let lo = 0, hi = a.length-1;\n  while (lo < hi) { const mid = (lo+hi)>>1; if (a[mid] > a[mid+1]) hi = mid; else lo = mid+1; }\n  console.log(lo); rl.close();\n});\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int[] a = Arrays.stream(sc.nextLine().split(\" \")).mapToInt(Integer::parseInt).toArray();\n        int lo = 0, hi = a.length-1;\n        while (lo < hi) { int mid = (lo+hi)/2; if (a[mid] > a[mid+1]) hi = mid; else lo = mid+1; }\n        System.out.println(lo);\n    }\n}\n`,
    },
  },
  {
    slug: 'kth-missing-positive',
    title: 'Kth Missing Positive Number',
    difficulty: 'Medium',
    category: 'Binary Search',
    tier: 'mid',
    acceptanceRate: 64.7,
    description: 'Given a strictly increasing array `arr` of positive integers and a positive integer `k`, return the `k`-th missing positive number. Input: first line is the array, second line is `k`.',
    constraints: '- `1 <= arr.length <= 1000`\n- `1 <= arr[i] <= 1000`\n- `1 <= k <= 1000`',
    examples: [{ input: '2 3 4 7 11\n5', output: '9', orderIndex: 0 }],
    testCases: [
      { input: '2 3 4 7 11\n5', expectedOutput: '9', isHidden: false, orderIndex: 0 },
      { input: '1 2 3 4\n2', expectedOutput: '6', isHidden: false, orderIndex: 1 },
      { input: '5 6\n1', expectedOutput: '1', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nlines = sys.stdin.read().split('\\n')\narr = list(map(int, lines[0].split()))\nk = int(lines[1])\nlo, hi = 0, len(arr)\nwhile lo < hi:\n    mid = (lo+hi)//2\n    if arr[mid] - (mid+1) >= k: hi = mid\n    else: lo = mid+1\nprint(lo + k)\n`,
      javascript: `const lines = require('fs').readFileSync('/dev/stdin','utf8').split('\\n');\nconst arr = lines[0].split(' ').map(Number);\nconst k = Number(lines[1]);\nlet lo = 0, hi = arr.length;\nwhile (lo < hi) { const mid = (lo+hi)>>1; if (arr[mid]-(mid+1) >= k) hi = mid; else lo = mid+1; }\nconsole.log(lo+k);\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int[] arr = Arrays.stream(sc.nextLine().split(\" \")).mapToInt(Integer::parseInt).toArray();\n        int k = sc.nextInt(), lo = 0, hi = arr.length;\n        while (lo < hi) { int mid = (lo+hi)/2; if (arr[mid]-(mid+1) >= k) hi = mid; else lo = mid+1; }\n        System.out.println(lo+k);\n    }\n}\n`,
    },
  },
  // ── HARD ─────────────────────────────────────────────────────────────────────
  {
    slug: 'median-two-sorted-arrays',
    title: 'Median of Two Sorted Arrays',
    difficulty: 'Hard',
    category: 'Binary Search',
    tier: 'pro',
    acceptanceRate: 38.2,
    description: 'Given two sorted arrays `nums1` and `nums2`, return the median of both arrays combined. The overall run time complexity must be O(log(m+n)). Input: first line is nums1, second line is nums2. Print with 5 decimal places.',
    constraints: '- `0 <= nums1.length, nums2.length <= 1000`\n- At least one array is non-empty\n- `-10^6 <= nums1[i], nums2[i] <= 10^6`',
    examples: [{ input: '1 3\n2', output: '2.00000', orderIndex: 0 }],
    testCases: [
      { input: '1 3\n2', expectedOutput: '2.00000', isHidden: false, orderIndex: 0 },
      { input: '1 2\n3 4', expectedOutput: '2.50000', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      python: `import sys\nlines = sys.stdin.read().split('\\n')\na = list(map(int, lines[0].split())) if lines[0].strip() else []\nb = list(map(int, lines[1].split())) if lines[1].strip() else []\nmerged = sorted(a+b)\nn = len(merged)\nif n % 2: print(f'{merged[n//2]:.5f}')\nelse: print(f'{(merged[n//2-1]+merged[n//2])/2:.5f}')\n`,
      javascript: `const lines = require('fs').readFileSync('/dev/stdin','utf8').split('\\n');\nconst a = lines[0].trim() ? lines[0].split(' ').map(Number) : [];\nconst b = lines[1].trim() ? lines[1].split(' ').map(Number) : [];\nconst m = [...a,...b].sort((x,y)=>x-y), n = m.length;\nconsole.log((n%2 ? m[n>>1] : (m[(n>>1)-1]+m[n>>1])/2).toFixed(5));\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int[] a = Arrays.stream(sc.nextLine().split(\" \")).mapToInt(Integer::parseInt).toArray();\n        int[] b = Arrays.stream(sc.nextLine().split(\" \")).mapToInt(Integer::parseInt).toArray();\n        int[] m = new int[a.length+b.length];\n        System.arraycopy(a,0,m,0,a.length); System.arraycopy(b,0,m,a.length,b.length);\n        Arrays.sort(m);\n        int n = m.length;\n        double med = n%2==1 ? m[n/2] : (m[n/2-1]+m[n/2])/2.0;\n        System.out.printf(\"%.5f%n\", med);\n    }\n}\n`,
    },
  },
  {
    slug: 'allocate-books',
    title: 'Allocate Books (Painter\'s Partition)',
    difficulty: 'Hard',
    category: 'Binary Search',
    tier: 'pro',
    acceptanceRate: 45.1,
    description: 'Given `n` books with page counts and `m` students, allocate books contiguously to each student to minimize the maximum pages any student gets. Each student must receive at least one book. Input: first line is the page counts, second line is `m`.',
    constraints: '- `1 <= n, m <= 10^5`\n- `1 <= pages[i] <= 10^6`\n- `m <= n`',
    examples: [{ input: '12 34 67 90\n2', output: '113', orderIndex: 0 }],
    testCases: [
      { input: '12 34 67 90\n2', expectedOutput: '113', isHidden: false, orderIndex: 0 },
      { input: '10 20 30 40\n2', expectedOutput: '60', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      python: `import sys\nlines = sys.stdin.read().split('\\n')\npages = list(map(int, lines[0].split()))\nm = int(lines[1])\ndef can_alloc(mid):\n    students, cur = 1, 0\n    for p in pages:\n        if cur + p > mid: students += 1; cur = p\n        else: cur += p\n    return students <= m\nlo, hi = max(pages), sum(pages)\nwhile lo < hi:\n    mid = (lo+hi)//2\n    if can_alloc(mid): hi = mid\n    else: lo = mid+1\nprint(lo)\n`,
      javascript: `const lines = require('fs').readFileSync('/dev/stdin','utf8').split('\\n');\nconst pages = lines[0].split(' ').map(Number), m = Number(lines[1]);\nconst ok = (mid) => { let s=1,c=0; for(const p of pages){if(c+p>mid){s++;c=p;}else c+=p;} return s<=m; };\nlet lo = Math.max(...pages), hi = pages.reduce((a,b)=>a+b,0);\nwhile(lo<hi){const mid=(lo+hi)>>1; if(ok(mid))hi=mid; else lo=mid+1;}\nconsole.log(lo);\n`,
      java: `import java.util.*;\npublic class Main {\n    static int[] pages; static int m;\n    static boolean ok(long mid) { int s=1; long c=0; for(int p:pages){if(c+p>mid){s++;c=p;}else c+=p;} return s<=m; }\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        pages = Arrays.stream(sc.nextLine().split(\" \")).mapToInt(Integer::parseInt).toArray();\n        m = sc.nextInt();\n        long lo = Arrays.stream(pages).max().getAsInt(), hi = Arrays.stream(pages).asLongStream().sum();\n        while(lo<hi){long mid=(lo+hi)/2; if(ok(mid))hi=mid; else lo=mid+1;}\n        System.out.println(lo);\n    }\n}\n`,
    },
  },
];
