/**
 * Step 3: Arrays — Easy / Medium / Hard
 * Tier: Easy → 'free' | Medium → 'mid' | Hard → 'pro'
 */
export const step3Problems = [
  // ── EASY ────────────────────────────────────────────────────────────────────
  {
    slug: 'largest-element-array',
    title: 'Largest Element in Array',
    difficulty: 'Easy',
    category: 'Array',
    tier: 'free',
    acceptanceRate: 88.0,
    description: 'Given an array of integers `nums`, return the largest element.',
    constraints: '- `1 <= nums.length <= 10^5`\n- `-10^9 <= nums[i] <= 10^9`',
    examples: [{ input: '3 1 4 1 5 9 2 6', output: '9', orderIndex: 0 }],
    testCases: [
      { input: '3 1 4 1 5 9 2 6', expectedOutput: '9', isHidden: false, orderIndex: 0 },
      { input: '-5 -1 -3', expectedOutput: '-1', isHidden: false, orderIndex: 1 },
      { input: '7', expectedOutput: '7', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nnums = list(map(int, sys.stdin.read().split()))\nprint(max(nums))\n`,
      javascript: `const rl = require('readline').createInterface({ input: process.stdin });\nrl.on('line', l => { console.log(Math.max(...l.split(' ').map(Number))); rl.close(); });\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int max = Integer.MIN_VALUE;\n        while (sc.hasNextInt()) max = Math.max(max, sc.nextInt());\n        System.out.println(max);\n    }\n}\n`,
    },
  },
  {
    slug: 'second-largest-element',
    title: 'Second Largest Element in Array',
    difficulty: 'Easy',
    category: 'Array',
    tier: 'free',
    acceptanceRate: 82.3,
    description: 'Given an array of integers `nums` with at least 2 distinct values, return the second largest element.',
    constraints: '- `2 <= nums.length <= 10^5`\n- All elements are distinct\n- `-10^9 <= nums[i] <= 10^9`',
    examples: [{ input: '10 5 8 20 15', output: '15', orderIndex: 0 }],
    testCases: [
      { input: '10 5 8 20 15', expectedOutput: '15', isHidden: false, orderIndex: 0 },
      { input: '1 2', expectedOutput: '1', isHidden: false, orderIndex: 1 },
      { input: '100 50 75 25', expectedOutput: '75', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nnums = list(map(int, sys.stdin.read().split()))\nnums.sort(reverse=True)\nprint(nums[1])\n`,
      javascript: `const rl = require('readline').createInterface({ input: process.stdin });\nrl.on('line', l => {\n  const a = l.split(' ').map(Number).sort((a,b) => b-a);\n  console.log(a[1]);\n  rl.close();\n});\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        List<Integer> list = new ArrayList<>();\n        while (sc.hasNextInt()) list.add(sc.nextInt());\n        list.sort(Collections.reverseOrder());\n        System.out.println(list.get(1));\n    }\n}\n`,
    },
  },
  {
    slug: 'check-sorted-array',
    title: 'Check if Array is Sorted',
    difficulty: 'Easy',
    category: 'Array',
    tier: 'free',
    acceptanceRate: 86.1,
    description: 'Given an integer array `nums`, return `true` if it is sorted in non-decreasing order, or `false` otherwise.',
    constraints: '- `1 <= nums.length <= 10^5`\n- `-10^9 <= nums[i] <= 10^9`',
    examples: [{ input: '1 2 2 3 5', output: 'true', orderIndex: 0 }],
    testCases: [
      { input: '1 2 2 3 5', expectedOutput: 'true', isHidden: false, orderIndex: 0 },
      { input: '5 3 4', expectedOutput: 'false', isHidden: false, orderIndex: 1 },
      { input: '7', expectedOutput: 'true', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nnums = list(map(int, sys.stdin.read().split()))\nprint(str(all(nums[i] <= nums[i+1] for i in range(len(nums)-1))).lower())\n`,
      javascript: `const rl = require('readline').createInterface({ input: process.stdin });\nrl.on('line', l => {\n  const a = l.split(' ').map(Number);\n  console.log(a.every((v,i) => i === 0 || a[i-1] <= v));\n  rl.close();\n});\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        List<Integer> a = new ArrayList<>();\n        while (sc.hasNextInt()) a.add(sc.nextInt());\n        boolean ok = true;\n        for (int i = 1; i < a.size(); i++) if (a.get(i) < a.get(i-1)) { ok = false; break; }\n        System.out.println(ok);\n    }\n}\n`,
    },
  },
  {
    slug: 'remove-duplicates-sorted',
    title: 'Remove Duplicates from Sorted Array',
    difficulty: 'Easy',
    category: 'Array',
    tier: 'free',
    acceptanceRate: 79.5,
    description: 'Given a sorted array `nums`, remove duplicates in-place and return the count of unique elements. Print that count followed by the unique elements separated by spaces.',
    constraints: '- `1 <= nums.length <= 3*10^4`\n- `-100 <= nums[i] <= 100`\n- `nums` is sorted in non-decreasing order',
    examples: [{ input: '1 1 2 2 3', output: '3\n1 2 3', orderIndex: 0 }],
    testCases: [
      { input: '1 1 2 2 3', expectedOutput: '3\n1 2 3', isHidden: false, orderIndex: 0 },
      { input: '0 0 1 1 1 2 2 3 3 4', expectedOutput: '5\n0 1 2 3 4', isHidden: false, orderIndex: 1 },
      { input: '5', expectedOutput: '1\n5', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nnums = list(map(int, sys.stdin.read().split()))\nuniq = list(dict.fromkeys(nums))\nprint(len(uniq))\nprint(*uniq)\n`,
      javascript: `const rl = require('readline').createInterface({ input: process.stdin });\nrl.on('line', l => {\n  const a = [...new Set(l.split(' ').map(Number))];\n  console.log(a.length);\n  console.log(a.join(' '));\n  rl.close();\n});\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        List<Integer> a = new ArrayList<>();\n        while (sc.hasNextInt()) a.add(sc.nextInt());\n        List<Integer> u = new ArrayList<>();\n        for (int x : a) if (u.isEmpty() || u.get(u.size()-1) != x) u.add(x);\n        System.out.println(u.size());\n        StringBuilder sb = new StringBuilder();\n        for (int i = 0; i < u.size(); i++) sb.append(u.get(i)).append(i < u.size()-1 ? \" \" : \"\");\n        System.out.println(sb);\n    }\n}\n`,
    },
  },
  {
    slug: 'rotate-array-by-k',
    title: 'Left Rotate Array by K Places',
    difficulty: 'Easy',
    category: 'Array',
    tier: 'free',
    acceptanceRate: 77.2,
    description: 'Given an array `nums` and integer `k`, rotate the array to the left by `k` positions and print the result.',
    constraints: '- `1 <= nums.length <= 10^5`\n- `0 <= k <= 10^5`',
    examples: [{ input: '1 2 3 4 5\n2', output: '3 4 5 1 2', orderIndex: 0 }],
    testCases: [
      { input: '1 2 3 4 5\n2', expectedOutput: '3 4 5 1 2', isHidden: false, orderIndex: 0 },
      { input: '1 2 3\n0', expectedOutput: '1 2 3', isHidden: false, orderIndex: 1 },
      { input: '7 8 9\n6', expectedOutput: '7 8 9', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nlines = sys.stdin.read().split('\\n')\nnums = list(map(int, lines[0].split()))\nk = int(lines[1]) % len(nums)\nprint(*(nums[k:] + nums[:k]))\n`,
      javascript: `const lines = require('fs').readFileSync('/dev/stdin','utf8').split('\\n');\nconst nums = lines[0].split(' ').map(Number);\nconst k = Number(lines[1]) % nums.length;\nconsole.log([...nums.slice(k), ...nums.slice(0,k)].join(' '));\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int[] nums = Arrays.stream(sc.nextLine().split(\" \")).mapToInt(Integer::parseInt).toArray();\n        int k = sc.nextInt() % nums.length;\n        int[] res = new int[nums.length];\n        for (int i = 0; i < nums.length; i++) res[i] = nums[(i + k) % nums.length];\n        StringBuilder sb = new StringBuilder();\n        for (int i = 0; i < res.length; i++) sb.append(res[i]).append(i < res.length-1?\" \":\"\");\n        System.out.println(sb);\n    }\n}\n`,
    },
  },
  {
    slug: 'move-zeroes-end',
    title: 'Move Zeroes to End',
    difficulty: 'Easy',
    category: 'Array',
    tier: 'free',
    acceptanceRate: 84.6,
    description: 'Given an array `nums`, move all `0`s to the end while maintaining the relative order of non-zero elements. Print the resulting array.',
    constraints: '- `1 <= nums.length <= 10^4`\n- `-2^31 <= nums[i] <= 2^31 - 1`',
    examples: [{ input: '0 1 0 3 12', output: '1 3 12 0 0', orderIndex: 0 }],
    testCases: [
      { input: '0 1 0 3 12', expectedOutput: '1 3 12 0 0', isHidden: false, orderIndex: 0 },
      { input: '0', expectedOutput: '0', isHidden: false, orderIndex: 1 },
      { input: '1 2 3', expectedOutput: '1 2 3', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nnums = list(map(int, sys.stdin.read().split()))\nnon_zero = [x for x in nums if x != 0]\nresult = non_zero + [0] * (len(nums) - len(non_zero))\nprint(*result)\n`,
      javascript: `const rl = require('readline').createInterface({ input: process.stdin });\nrl.on('line', l => {\n  const a = l.split(' ').map(Number);\n  const nz = a.filter(x => x !== 0);\n  while (nz.length < a.length) nz.push(0);\n  console.log(nz.join(' '));\n  rl.close();\n});\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int[] a = Arrays.stream(sc.nextLine().split(\" \")).mapToInt(Integer::parseInt).toArray();\n        int pos = 0;\n        for (int x : a) if (x != 0) a[pos++] = x;\n        while (pos < a.length) a[pos++] = 0;\n        StringBuilder sb = new StringBuilder();\n        for (int i = 0; i < a.length; i++) sb.append(a[i]).append(i<a.length-1?\" \":\"\");\n        System.out.println(sb);\n    }\n}\n`,
    },
  },
  {
    slug: 'union-of-sorted-arrays',
    title: 'Union of Two Sorted Arrays',
    difficulty: 'Easy',
    category: 'Array',
    tier: 'free',
    acceptanceRate: 75.1,
    description: 'Given two sorted arrays, return their union as a sorted array with no duplicates. Input: first line is array A, second line is array B.',
    constraints: '- `1 <= len(A), len(B) <= 10^5`\n- `-10^9 <= A[i], B[i] <= 10^9`',
    examples: [{ input: '1 2 4 5\n2 3 5 6', output: '1 2 3 4 5 6', orderIndex: 0 }],
    testCases: [
      { input: '1 2 4 5\n2 3 5 6', expectedOutput: '1 2 3 4 5 6', isHidden: false, orderIndex: 0 },
      { input: '1 1 2\n2 3', expectedOutput: '1 2 3', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      python: `import sys\nlines = sys.stdin.read().split('\\n')\na = list(map(int, lines[0].split()))\nb = list(map(int, lines[1].split()))\nprint(*sorted(set(a) | set(b)))\n`,
      javascript: `const lines = require('fs').readFileSync('/dev/stdin','utf8').split('\\n');\nconst a = lines[0].split(' ').map(Number);\nconst b = lines[1].split(' ').map(Number);\nconst u = [...new Set([...a,...b])].sort((x,y)=>x-y);\nconsole.log(u.join(' '));\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        TreeSet<Integer> s = new TreeSet<>();\n        for (String x : sc.nextLine().split(\" \")) s.add(Integer.parseInt(x));\n        for (String x : sc.nextLine().split(\" \")) s.add(Integer.parseInt(x));\n        StringBuilder sb = new StringBuilder();\n        Iterator<Integer> it = s.iterator();\n        while (it.hasNext()) { sb.append(it.next()); if (it.hasNext()) sb.append(' '); }\n        System.out.println(sb);\n    }\n}\n`,
    },
  },
  // ── MEDIUM ────────────────────────────────────────────────────────────────────
  {
    slug: 'two-sum-problem',
    title: 'Two Sum',
    difficulty: 'Medium',
    category: 'Array',
    tier: 'mid',
    acceptanceRate: 71.3,
    description: 'Given an integer array `nums` and a target integer `target`, return the 0-indexed positions of the two numbers that add up to `target`. You may assume exactly one solution exists. First line is the array, second line is the target.',
    constraints: '- `2 <= nums.length <= 10^4`\n- `-10^9 <= nums[i] <= 10^9`\n- Exactly one valid answer exists',
    examples: [{ input: '2 7 11 15\n9', output: '0 1', orderIndex: 0 }],
    testCases: [
      { input: '2 7 11 15\n9', expectedOutput: '0 1', isHidden: false, orderIndex: 0 },
      { input: '3 2 4\n6', expectedOutput: '1 2', isHidden: false, orderIndex: 1 },
      { input: '5 1 3 2\n4', expectedOutput: '2 3', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nlines = sys.stdin.read().split('\\n')\nnums = list(map(int, lines[0].split()))\ntarget = int(lines[1])\nseen = {}\nfor i, n in enumerate(nums):\n    if target - n in seen:\n        print(seen[target - n], i)\n        break\n    seen[n] = i\n`,
      javascript: `const lines = require('fs').readFileSync('/dev/stdin','utf8').split('\\n');\nconst nums = lines[0].split(' ').map(Number);\nconst target = Number(lines[1]);\nconst map = new Map();\nfor (let i = 0; i < nums.length; i++) {\n  if (map.has(target - nums[i])) { console.log(map.get(target-nums[i]) + ' ' + i); break; }\n  map.set(nums[i], i);\n}\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int[] nums = Arrays.stream(sc.nextLine().split(\" \")).mapToInt(Integer::parseInt).toArray();\n        int target = sc.nextInt();\n        Map<Integer,Integer> map = new HashMap<>();\n        for (int i = 0; i < nums.length; i++) {\n            if (map.containsKey(target - nums[i])) { System.out.println(map.get(target-nums[i]) + \" \" + i); return; }\n            map.put(nums[i], i);\n        }\n    }\n}\n`,
    },
  },
  {
    slug: 'sort-0s-1s-2s',
    title: 'Sort an Array of 0s, 1s, and 2s',
    difficulty: 'Medium',
    category: 'Array',
    tier: 'mid',
    acceptanceRate: 73.8,
    description: 'Given an array containing only 0s, 1s, and 2s, sort it in-place without using any built-in sort. Print the sorted array.',
    constraints: '- `1 <= nums.length <= 3*10^4`\n- `nums[i] is 0, 1, or 2`',
    examples: [{ input: '2 0 2 1 1 0', output: '0 0 1 1 2 2', orderIndex: 0 }],
    testCases: [
      { input: '2 0 2 1 1 0', expectedOutput: '0 0 1 1 2 2', isHidden: false, orderIndex: 0 },
      { input: '2 0 1', expectedOutput: '0 1 2', isHidden: false, orderIndex: 1 },
      { input: '0 0 0', expectedOutput: '0 0 0', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nnums = list(map(int, sys.stdin.read().split()))\nlo, mid, hi = 0, 0, len(nums) - 1\nwhile mid <= hi:\n    if nums[mid] == 0: nums[lo], nums[mid] = nums[mid], nums[lo]; lo += 1; mid += 1\n    elif nums[mid] == 1: mid += 1\n    else: nums[mid], nums[hi] = nums[hi], nums[mid]; hi -= 1\nprint(*nums)\n`,
      javascript: `const rl = require('readline').createInterface({ input: process.stdin });\nrl.on('line', l => {\n  const a = l.split(' ').map(Number);\n  let lo = 0, mid = 0, hi = a.length - 1;\n  while (mid <= hi) {\n    if (a[mid] === 0) { [a[lo],a[mid]] = [a[mid],a[lo]]; lo++; mid++; }\n    else if (a[mid] === 1) mid++;\n    else { [a[mid],a[hi]] = [a[hi],a[mid]]; hi--; }\n  }\n  console.log(a.join(' ')); rl.close();\n});\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int[] a = Arrays.stream(sc.nextLine().split(\" \")).mapToInt(Integer::parseInt).toArray();\n        int lo = 0, mid = 0, hi = a.length - 1;\n        while (mid <= hi) {\n            if (a[mid] == 0) { int t = a[lo]; a[lo] = a[mid]; a[mid] = t; lo++; mid++; }\n            else if (a[mid] == 1) mid++;\n            else { int t = a[mid]; a[mid] = a[hi]; a[hi] = t; hi--; }\n        }\n        StringBuilder sb = new StringBuilder();\n        for (int i = 0; i < a.length; i++) sb.append(a[i]).append(i<a.length-1?\" \":\"\");\n        System.out.println(sb);\n    }\n}\n`,
    },
  },
  {
    slug: 'maximum-subarray-sum',
    title: 'Maximum Subarray Sum (Kadane\'s Algorithm)',
    difficulty: 'Medium',
    category: 'Array',
    tier: 'mid',
    acceptanceRate: 68.4,
    description: 'Given an integer array `nums`, find the contiguous subarray (with at least one element) that has the largest sum and return that sum.',
    constraints: '- `1 <= nums.length <= 10^5`\n- `-10^4 <= nums[i] <= 10^4`',
    examples: [{ input: '-2 1 -3 4 -1 2 1 -5 4', output: '6', explanation: 'Subarray [4,-1,2,1] has sum 6', orderIndex: 0 }],
    testCases: [
      { input: '-2 1 -3 4 -1 2 1 -5 4', expectedOutput: '6', isHidden: false, orderIndex: 0 },
      { input: '1', expectedOutput: '1', isHidden: false, orderIndex: 1 },
      { input: '-3 -1 -2', expectedOutput: '-1', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nnums = list(map(int, sys.stdin.read().split()))\ncur = best = nums[0]\nfor x in nums[1:]:\n    cur = max(x, cur + x)\n    best = max(best, cur)\nprint(best)\n`,
      javascript: `const rl = require('readline').createInterface({ input: process.stdin });\nrl.on('line', l => {\n  const a = l.split(' ').map(Number);\n  let cur = a[0], best = a[0];\n  for (let i = 1; i < a.length; i++) { cur = Math.max(a[i], cur+a[i]); best = Math.max(best, cur); }\n  console.log(best); rl.close();\n});\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int[] a = Arrays.stream(sc.nextLine().split(\" \")).mapToInt(Integer::parseInt).toArray();\n        int cur = a[0], best = a[0];\n        for (int i = 1; i < a.length; i++) { cur = Math.max(a[i], cur+a[i]); best = Math.max(best, cur); }\n        System.out.println(best);\n    }\n}\n`,
    },
  },
  {
    slug: 'best-time-buy-sell',
    title: 'Best Time to Buy and Sell Stock',
    difficulty: 'Medium',
    category: 'Array',
    tier: 'mid',
    acceptanceRate: 72.0,
    description: 'Given an array `prices` where `prices[i]` is the price of a stock on day `i`, return the maximum profit achievable by buying on one day and selling on a later day. Return 0 if no profit is possible.',
    constraints: '- `1 <= prices.length <= 10^5`\n- `0 <= prices[i] <= 10^4`',
    examples: [{ input: '7 1 5 3 6 4', output: '5', orderIndex: 0 }],
    testCases: [
      { input: '7 1 5 3 6 4', expectedOutput: '5', isHidden: false, orderIndex: 0 },
      { input: '7 6 4 3 1', expectedOutput: '0', isHidden: false, orderIndex: 1 },
      { input: '1 2', expectedOutput: '1', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nprices = list(map(int, sys.stdin.read().split()))\nmin_p, profit = prices[0], 0\nfor p in prices[1:]:\n    profit = max(profit, p - min_p)\n    min_p = min(min_p, p)\nprint(profit)\n`,
      javascript: `const rl = require('readline').createInterface({ input: process.stdin });\nrl.on('line', l => {\n  const p = l.split(' ').map(Number);\n  let minP = p[0], profit = 0;\n  for (let i = 1; i < p.length; i++) { profit = Math.max(profit, p[i]-minP); minP = Math.min(minP, p[i]); }\n  console.log(profit); rl.close();\n});\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int[] p = Arrays.stream(sc.nextLine().split(\" \")).mapToInt(Integer::parseInt).toArray();\n        int minP = p[0], profit = 0;\n        for (int i = 1; i < p.length; i++) { profit = Math.max(profit, p[i]-minP); minP = Math.min(minP, p[i]); }\n        System.out.println(profit);\n    }\n}\n`,
    },
  },
  {
    slug: 'rearrange-alternating',
    title: 'Rearrange Array Elements by Sign',
    difficulty: 'Medium',
    category: 'Array',
    tier: 'mid',
    acceptanceRate: 65.7,
    description: 'Given an equal-count array of positive and negative integers, rearrange so positives and negatives alternate, starting with a positive. Maintain the relative order within each sign group. Print the result.',
    constraints: '- `2 <= nums.length <= 2*10^5`\n- Equal number of positives and negatives\n- No element is zero',
    examples: [{ input: '3 1 -2 -5 2 -4', output: '3 -2 1 -5 2 -4', orderIndex: 0 }],
    testCases: [
      { input: '3 1 -2 -5 2 -4', expectedOutput: '3 -2 1 -5 2 -4', isHidden: false, orderIndex: 0 },
      { input: '-1 1', expectedOutput: '1 -1', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      python: `import sys\nnums = list(map(int, sys.stdin.read().split()))\npos = [x for x in nums if x > 0]\nneg = [x for x in nums if x < 0]\nres = []\nfor p, n in zip(pos, neg):\n    res.append(p); res.append(n)\nprint(*res)\n`,
      javascript: `const rl = require('readline').createInterface({ input: process.stdin });\nrl.on('line', l => {\n  const a = l.split(' ').map(Number);\n  const pos = a.filter(x => x > 0), neg = a.filter(x => x < 0);\n  const res = [];\n  pos.forEach((p,i) => { res.push(p); res.push(neg[i]); });\n  console.log(res.join(' ')); rl.close();\n});\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int[] a = Arrays.stream(sc.nextLine().split(\" \")).mapToInt(Integer::parseInt).toArray();\n        List<Integer> pos = new ArrayList<>(), neg = new ArrayList<>();\n        for (int x : a) { if (x > 0) pos.add(x); else neg.add(x); }\n        StringBuilder sb = new StringBuilder();\n        for (int i = 0; i < pos.size(); i++) { if (i > 0) sb.append(' '); sb.append(pos.get(i)).append(' ').append(neg.get(i)); }\n        System.out.println(sb);\n    }\n}\n`,
    },
  },
  {
    slug: 'majority-element-moore',
    title: 'Majority Element (Moore Voting)',
    difficulty: 'Medium',
    category: 'Array',
    tier: 'mid',
    acceptanceRate: 69.2,
    description: 'Given an array `nums` of size `n`, return the element that appears more than `n/2` times. A majority element always exists.',
    constraints: '- `1 <= nums.length <= 5*10^4`\n- A majority element always exists',
    examples: [{ input: '2 2 1 1 1 2 2', output: '2', orderIndex: 0 }],
    testCases: [
      { input: '2 2 1 1 1 2 2', expectedOutput: '2', isHidden: false, orderIndex: 0 },
      { input: '3 2 3', expectedOutput: '3', isHidden: false, orderIndex: 1 },
      { input: '1', expectedOutput: '1', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nnums = list(map(int, sys.stdin.read().split()))\ncand, count = nums[0], 1\nfor x in nums[1:]:\n    if count == 0: cand, count = x, 1\n    elif x == cand: count += 1\n    else: count -= 1\nprint(cand)\n`,
      javascript: `const rl = require('readline').createInterface({ input: process.stdin });\nrl.on('line', l => {\n  const a = l.split(' ').map(Number);\n  let cand = a[0], cnt = 1;\n  for (let i = 1; i < a.length; i++) {\n    if (cnt === 0) { cand = a[i]; cnt = 1; } else if (a[i] === cand) cnt++; else cnt--;\n  }\n  console.log(cand); rl.close();\n});\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int[] a = Arrays.stream(sc.nextLine().split(\" \")).mapToInt(Integer::parseInt).toArray();\n        int cand = a[0], cnt = 1;\n        for (int i = 1; i < a.length; i++) {\n            if (cnt == 0) { cand = a[i]; cnt = 1; } else if (a[i] == cand) cnt++; else cnt--;\n        }\n        System.out.println(cand);\n    }\n}\n`,
    },
  },
  // ── HARD ─────────────────────────────────────────────────────────────────────
  {
    slug: 'trapping-rain-water',
    title: 'Trapping Rain Water',
    difficulty: 'Hard',
    category: 'Array',
    tier: 'pro',
    acceptanceRate: 54.2,
    description: 'Given `n` non-negative integers representing an elevation map where the width of each bar is 1, compute how much water can be trapped after raining.',
    constraints: '- `n == height.length`\n- `1 <= n <= 2*10^4`\n- `0 <= height[i] <= 10^5`',
    examples: [{ input: '0 1 0 2 1 0 1 3 2 1 2 1', output: '6', orderIndex: 0 }],
    testCases: [
      { input: '0 1 0 2 1 0 1 3 2 1 2 1', expectedOutput: '6', isHidden: false, orderIndex: 0 },
      { input: '4 2 0 3 2 5', expectedOutput: '9', isHidden: false, orderIndex: 1 },
      { input: '3 0 0 2 0 4', expectedOutput: '10', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nh = list(map(int, sys.stdin.read().split()))\nn = len(h)\nleft, right = 0, n - 1\nlmax = rmax = water = 0\nwhile left < right:\n    if h[left] <= h[right]:\n        if h[left] >= lmax: lmax = h[left]\n        else: water += lmax - h[left]\n        left += 1\n    else:\n        if h[right] >= rmax: rmax = h[right]\n        else: water += rmax - h[right]\n        right -= 1\nprint(water)\n`,
      javascript: `const rl = require('readline').createInterface({ input: process.stdin });\nrl.on('line', l => {\n  const h = l.split(' ').map(Number);\n  let l2 = 0, r = h.length-1, lm = 0, rm = 0, w = 0;\n  while (l2 < r) {\n    if (h[l2] <= h[r]) { if (h[l2] >= lm) lm = h[l2]; else w += lm-h[l2]; l2++; }\n    else { if (h[r] >= rm) rm = h[r]; else w += rm-h[r]; r--; }\n  }\n  console.log(w); rl.close();\n});\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int[] h = Arrays.stream(sc.nextLine().split(\" \")).mapToInt(Integer::parseInt).toArray();\n        int l = 0, r = h.length-1, lm = 0, rm = 0, w = 0;\n        while (l < r) {\n            if (h[l] <= h[r]) { if (h[l] >= lm) lm = h[l]; else w += lm-h[l]; l++; }\n            else { if (h[r] >= rm) rm = h[r]; else w += rm-h[r]; r--; }\n        }\n        System.out.println(w);\n    }\n}\n`,
    },
  },
  {
    slug: 'merge-overlapping-intervals',
    title: 'Merge Overlapping Intervals',
    difficulty: 'Hard',
    category: 'Array',
    tier: 'pro',
    acceptanceRate: 57.8,
    description: 'Given a list of intervals where each interval is `[start end]`, merge all overlapping intervals and return the result. Input: first line is count `n`, then `n` lines each with `start end`. Output: each merged interval on its own line.',
    constraints: '- `1 <= intervals.length <= 10^4`\n- `0 <= start <= end <= 10^4`',
    examples: [{ input: '4\n1 3\n2 6\n8 10\n15 18', output: '1 6\n8 10\n15 18', orderIndex: 0 }],
    testCases: [
      { input: '4\n1 3\n2 6\n8 10\n15 18', expectedOutput: '1 6\n8 10\n15 18', isHidden: false, orderIndex: 0 },
      { input: '2\n1 4\n4 5', expectedOutput: '1 5', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      python: `import sys\nlines = sys.stdin.read().split('\\n')\nn = int(lines[0])\nintervals = [list(map(int, lines[i+1].split())) for i in range(n)]\nintervals.sort()\nmerged = [intervals[0]]\nfor s, e in intervals[1:]:\n    if s <= merged[-1][1]:\n        merged[-1][1] = max(merged[-1][1], e)\n    else:\n        merged.append([s, e])\nfor a, b in merged:\n    print(a, b)\n`,
      javascript: `const lines = require('fs').readFileSync('/dev/stdin','utf8').split('\\n');\nconst n = parseInt(lines[0]);\nconst ivs = [];\nfor (let i = 1; i <= n; i++) { const [a,b] = lines[i].split(' ').map(Number); ivs.push([a,b]); }\nivs.sort((a,b) => a[0]-b[0]);\nconst m = [ivs[0]];\nfor (let i = 1; i < ivs.length; i++) {\n  if (ivs[i][0] <= m[m.length-1][1]) m[m.length-1][1] = Math.max(m[m.length-1][1], ivs[i][1]);\n  else m.push(ivs[i]);\n}\nm.forEach(([a,b]) => console.log(a+' '+b));\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[][] iv = new int[n][2];\n        for (int i = 0; i < n; i++) { iv[i][0] = sc.nextInt(); iv[i][1] = sc.nextInt(); }\n        Arrays.sort(iv, (a,b) -> a[0]-b[0]);\n        List<int[]> m = new ArrayList<>();\n        m.add(iv[0]);\n        for (int i = 1; i < n; i++) {\n            int[] last = m.get(m.size()-1);\n            if (iv[i][0] <= last[1]) last[1] = Math.max(last[1], iv[i][1]);\n            else m.add(iv[i]);\n        }\n        for (int[] a : m) System.out.println(a[0] + \" \" + a[1]);\n    }\n}\n`,
    },
  },
  {
    slug: 'four-sum-problem',
    title: 'Four Sum',
    difficulty: 'Hard',
    category: 'Array',
    tier: 'pro',
    acceptanceRate: 44.6,
    description: 'Given an integer array `nums` and a target value, return all unique quadruplets `[a,b,c,d]` such that `a+b+c+d == target`. Input: first line is the array, second line is the target. Each quadruplet printed as four space-separated numbers on its own line, sorted in non-decreasing order.',
    constraints: '- `4 <= nums.length <= 200`\n- `-10^9 <= nums[i] <= 10^9`\n- `-10^9 <= target <= 10^9`',
    examples: [{ input: '1 0 -1 0 -2 2\n0', output: '-2 -1 1 2\n-2 0 0 2\n-1 0 0 1', orderIndex: 0 }],
    testCases: [
      { input: '1 0 -1 0 -2 2\n0', expectedOutput: '-2 -1 1 2\n-2 0 0 2\n-1 0 0 1', isHidden: false, orderIndex: 0 },
      { input: '2 2 2 2 2\n8', expectedOutput: '2 2 2 2', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      python: `import sys\nlines = sys.stdin.read().split('\\n')\nnums = sorted(map(int, lines[0].split()))\ntarget = int(lines[1])\nn = len(nums)\nresults = set()\nfor i in range(n-3):\n    for j in range(i+1, n-2):\n        l, r = j+1, n-1\n        while l < r:\n            s = nums[i]+nums[j]+nums[l]+nums[r]\n            if s == target: results.add((nums[i],nums[j],nums[l],nums[r])); l += 1; r -= 1\n            elif s < target: l += 1\n            else: r -= 1\nfor quad in sorted(results):\n    print(*quad)\n`,
      javascript: `const lines = require('fs').readFileSync('/dev/stdin','utf8').split('\\n');\nconst nums = lines[0].split(' ').map(Number).sort((a,b)=>a-b);\nconst target = Number(lines[1]), n = nums.length;\nconst res = new Set();\nfor (let i = 0; i < n-3; i++) for (let j = i+1; j < n-2; j++) {\n  let l = j+1, r = n-1;\n  while (l < r) {\n    const s = nums[i]+nums[j]+nums[l]+nums[r];\n    if (s === target) { res.add([nums[i],nums[j],nums[l],nums[r]].join(',')); l++; r--; }\n    else if (s < target) l++; else r--;\n  }\n}\n[...res].sort().forEach(q => console.log(q.replace(/,/g,' ')));\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int[] nums = Arrays.stream(sc.nextLine().split(\" \")).mapToInt(Integer::parseInt).sorted().toArray();\n        long target = sc.nextLong();\n        int n = nums.length;\n        Set<String> res = new TreeSet<>();\n        for (int i = 0; i < n-3; i++) for (int j = i+1; j < n-2; j++) {\n            int l = j+1, r = n-1;\n            while (l < r) {\n                long s = (long)nums[i]+nums[j]+nums[l]+nums[r];\n                if (s == target) { res.add(nums[i]+\" \"+nums[j]+\" \"+nums[l]+\" \"+nums[r]); l++; r--; }\n                else if (s < target) l++; else r--;\n            }\n        }\n        res.forEach(System.out::println);\n    }\n}\n`,
    },
  },
];
