/**
 * Step 1: Learn the Basics (31 problems)
 * Tier mapping: Easy → 'free', Medium → 'mid', Hard → 'pro'
 */
export const step1Problems = [
  {
    slug: 'user-input-output',
    title: 'User Input and Output',
    difficulty: 'Easy',
    category: 'Basics',
    tier: 'free',
    acceptanceRate: 92.1,
    description: 'Read an integer `x` from standard input and print `x + 1` to standard output.',
    constraints: '- `0 <= x <= 10^6`',
    examples: [{ input: '5', output: '6', orderIndex: 0 }],
    testCases: [
      { input: '5', expectedOutput: '6', isHidden: false, orderIndex: 0 },
      { input: '0', expectedOutput: '1', isHidden: false, orderIndex: 1 },
      { input: '99', expectedOutput: '100', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nx = int(sys.stdin.read().strip())\nprint(x + 1)\n`,
      javascript: `const readline = require('readline');\nconst rl = readline.createInterface({ input: process.stdin });\nrl.on('line', l => { console.log(Number(l.trim()) + 1); rl.close(); });\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        System.out.println(sc.nextInt() + 1);\n    }\n}\n`,
    },
  },
  {
    slug: 'data-types-size',
    title: 'Data Types and Memory Size',
    difficulty: 'Easy',
    category: 'Basics',
    tier: 'free',
    acceptanceRate: 88.5,
    description: 'Given a primitive data type name (`Integer`, `Long`, `Float`, `Double`, `Character`), return its size in bytes.',
    constraints: 'Input is a string representing a primitive data type.',
    examples: [{ input: 'Integer', output: '4', orderIndex: 0 }],
    testCases: [
      { input: 'Integer', expectedOutput: '4', isHidden: false, orderIndex: 0 },
      { input: 'Long', expectedOutput: '8', isHidden: false, orderIndex: 1 },
      { input: 'Character', expectedOutput: '2', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nt = sys.stdin.read().strip()\nsizes = {'Character': 2, 'Integer': 4, 'Float': 4, 'Long': 8, 'Double': 8}\nprint(sizes.get(t, 4))\n`,
      javascript: `const readline = require('readline');\nconst rl = readline.createInterface({ input: process.stdin });\nrl.on('line', l => {\n  const s = { Character: 2, Integer: 4, Float: 4, Long: 8, Double: 8 };\n  console.log(s[l.trim()] || 4);\n  rl.close();\n});\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.next();\n        if (s.equals("Character")) System.out.println(2);\n        else if (s.equals("Integer") || s.equals("Float")) System.out.println(4);\n        else System.out.println(8);\n    }\n}\n`,
    },
  },
  {
    slug: 'if-else-decision',
    title: 'If-Else Decision Making',
    difficulty: 'Easy',
    category: 'Basics',
    tier: 'free',
    acceptanceRate: 85.0,
    description: 'Given two numbers `n` and `m`, print `Greater` if `n > m`, `Lesser` if `n < m`, and `Equal` if `n == m`.',
    constraints: '- `-10^9 <= n, m <= 10^9`',
    examples: [{ input: '5 3', output: 'Greater', orderIndex: 0 }],
    testCases: [
      { input: '5 3', expectedOutput: 'Greater', isHidden: false, orderIndex: 0 },
      { input: '2 8', expectedOutput: 'Lesser', isHidden: false, orderIndex: 1 },
      { input: '4 4', expectedOutput: 'Equal', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nn, m = map(int, sys.stdin.read().split())\nif n > m: print('Greater')\nelif n < m: print('Lesser')\nelse: print('Equal')\n`,
      javascript: `const readline = require('readline');\nconst rl = readline.createInterface({ input: process.stdin });\nrl.on('line', l => {\n  const [n, m] = l.split(' ').map(Number);\n  if (n > m) console.log('Greater');\n  else if (n < m) console.log('Lesser');\n  else console.log('Equal');\n  rl.close();\n});\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt(), m = sc.nextInt();\n        if (n > m) System.out.println("Greater");\n        else if (n < m) System.out.println("Lesser");\n        else System.out.println("Equal");\n    }\n}\n`,
    },
  },
  {
    slug: 'count-digits',
    title: 'Count Digits',
    difficulty: 'Easy',
    category: 'Math',
    tier: 'free',
    acceptanceRate: 82.3,
    description: 'Given a positive integer `n`, return the count of digits in `n`.',
    constraints: '- `1 <= n <= 10^9`',
    examples: [{ input: '12345', output: '5', orderIndex: 0 }],
    testCases: [
      { input: '12345', expectedOutput: '5', isHidden: false, orderIndex: 0 },
      { input: '7', expectedOutput: '1', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      python: `import sys\nprint(len(sys.stdin.read().strip()))\n`,
      javascript: `const readline = require('readline');\nconst rl = readline.createInterface({ input: process.stdin });\nrl.on('line', l => { console.log(l.trim().length); rl.close(); });\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        System.out.println(sc.next().length());\n    }\n}\n`,
    },
  },
  {
    slug: 'reverse-number',
    title: 'Reverse a Number',
    difficulty: 'Easy',
    category: 'Math',
    tier: 'free',
    acceptanceRate: 78.1,
    description: 'Reverse the digits of a 32-bit signed integer `x`. Return 0 if reversing causes overflow.',
    constraints: '- `-2^31 <= x <= 2^31 - 1`',
    examples: [{ input: '123', output: '321', orderIndex: 0 }],
    testCases: [
      { input: '123', expectedOutput: '321', isHidden: false, orderIndex: 0 },
      { input: '-123', expectedOutput: '-321', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      python: `import sys\nx = int(sys.stdin.read().strip())\nsign = -1 if x < 0 else 1\nrev = int(str(abs(x))[::-1]) * sign\nprint(rev if -2**31 <= rev <= 2**31 - 1 else 0)\n`,
      javascript: `const readline = require('readline');\nconst rl = readline.createInterface({ input: process.stdin });\nrl.on('line', l => {\n  const x = Number(l.trim());\n  const sign = x < 0 ? -1 : 1;\n  const rev = Number(Math.abs(x).toString().split('').reverse().join('')) * sign;\n  console.log(rev >= -2147483648 && rev <= 2147483647 ? rev : 0);\n  rl.close();\n});\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int x = sc.nextInt();\n        int rev = 0;\n        while (x != 0) {\n            int pop = x % 10; x /= 10;\n            if (rev > Integer.MAX_VALUE/10 || rev < Integer.MIN_VALUE/10) { System.out.println(0); return; }\n            rev = rev * 10 + pop;\n        }\n        System.out.println(rev);\n    }\n}\n`,
    },
  },
  {
    slug: 'armstrong-numbers',
    title: 'Check Armstrong Number',
    difficulty: 'Easy',
    category: 'Math',
    tier: 'free',
    acceptanceRate: 75.4,
    description: 'Check if a number `N` is an Armstrong number (sum of digits raised to power of digit count equals N).',
    constraints: '- `1 <= N <= 10^9`',
    examples: [{ input: '153', output: 'true', orderIndex: 0 }],
    testCases: [
      { input: '153', expectedOutput: 'true', isHidden: false, orderIndex: 0 },
      { input: '123', expectedOutput: 'false', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      python: `import sys\ns = sys.stdin.read().strip()\nk = len(s)\nprint(str(sum(int(c)**k for c in s) == int(s)).lower())\n`,
      javascript: `const readline = require('readline');\nconst rl = readline.createInterface({ input: process.stdin });\nrl.on('line', l => {\n  const s = l.trim();\n  const k = s.length;\n  const sum = s.split('').reduce((a, c) => a + Math.pow(Number(c), k), 0);\n  console.log(sum === Number(s));\n  rl.close();\n});\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.next();\n        int k = s.length(), sum = 0, orig = Integer.parseInt(s);\n        for (char c : s.toCharArray()) sum += Math.pow(c - '0', k);\n        System.out.println(sum == orig);\n    }\n}\n`,
    },
  },
  {
    slug: 'gcd-hcf-euclidean',
    title: 'GCD or HCF Calculation',
    difficulty: 'Easy',
    category: 'Math',
    tier: 'free',
    acceptanceRate: 80.2,
    description: 'Calculate the Greatest Common Divisor (GCD) of two numbers `a` and `b`.',
    constraints: '- `1 <= a, b <= 10^9`',
    examples: [{ input: '12 18', output: '6', orderIndex: 0 }],
    testCases: [
      { input: '12 18', expectedOutput: '6', isHidden: false, orderIndex: 0 },
      { input: '25 15', expectedOutput: '5', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      python: `import sys, math\na, b = map(int, sys.stdin.read().split())\nprint(math.gcd(a, b))\n`,
      javascript: `const readline = require('readline');\nconst rl = readline.createInterface({ input: process.stdin });\nrl.on('line', l => {\n  const [a, b] = l.split(' ').map(Number);\n  const gcd = (x, y) => y === 0 ? x : gcd(y, x % y);\n  console.log(gcd(a, b));\n  rl.close();\n});\n`,
      java: `import java.util.*;\npublic class Main {\n    static int gcd(int a, int b) { return b == 0 ? a : gcd(b, a % b); }\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        System.out.println(gcd(sc.nextInt(), sc.nextInt()));\n    }\n}\n`,
    },
  },
  {
    slug: 'print-all-divisors',
    title: 'Print All Divisors of a Number',
    difficulty: 'Easy',
    category: 'Math',
    tier: 'free',
    acceptanceRate: 76.9,
    description: 'Given an integer `n`, print all unique divisors of `n` in sorted space-separated order.',
    constraints: '- `1 <= n <= 10^6`',
    examples: [{ input: '36', output: '1 2 3 4 6 9 12 18 36', orderIndex: 0 }],
    testCases: [
      { input: '36', expectedOutput: '1 2 3 4 6 9 12 18 36', isHidden: false, orderIndex: 0 },
      { input: '7', expectedOutput: '1 7', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      python: `import sys, math\nn = int(sys.stdin.read().strip())\ndivs = set()\nfor i in range(1, int(math.isqrt(n)) + 1):\n    if n % i == 0:\n        divs.add(i)\n        divs.add(n // i)\nprint(*sorted(divs))\n`,
      javascript: `const readline = require('readline');\nconst rl = readline.createInterface({ input: process.stdin });\nrl.on('line', l => {\n  const n = Number(l.trim());\n  const divs = new Set();\n  for (let i = 1; i * i <= n; i++) {\n    if (n % i === 0) { divs.add(i); divs.add(Math.floor(n / i)); }\n  }\n  console.log([...divs].sort((a,b)=>a-b).join(' '));\n  rl.close();\n});\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        Set<Integer> divs = new TreeSet<>();\n        for (int i = 1; i * i <= n; i++) {\n            if (n % i == 0) { divs.add(i); divs.add(n / i); }\n        }\n        List<Integer> list = new ArrayList<>(divs);\n        for (int i = 0; i < list.size(); i++) System.out.print(list.get(i) + (i == list.size() - 1 ? "" : " "));\n        System.out.println();\n    }\n}\n`,
    },
  },
  {
    slug: 'check-for-prime',
    title: 'Check Prime Number',
    difficulty: 'Easy',
    category: 'Math',
    tier: 'free',
    acceptanceRate: 79.1,
    description: 'Check if a given positive integer `n` is prime.',
    constraints: '- `1 <= n <= 10^9`',
    examples: [{ input: '11', output: 'true', orderIndex: 0 }],
    testCases: [
      { input: '11', expectedOutput: 'true', isHidden: false, orderIndex: 0 },
      { input: '4', expectedOutput: 'false', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      python: `import sys, math\nn = int(sys.stdin.read().strip())\nif n <= 1: print('false'); exit()\nis_p = True\nfor i in range(2, int(math.isqrt(n)) + 1):\n    if n % i == 0: is_p = False; break\nprint(str(is_p).lower())\n`,
      javascript: `const readline = require('readline');\nconst rl = readline.createInterface({ input: process.stdin });\nrl.on('line', l => {\n  const n = Number(l.trim());\n  if (n <= 1) { console.log(false); rl.close(); return; }\n  let isP = true;\n  for (let i = 2; i * i <= n; i++) if (n % i === 0) { isP = false; break; }\n  console.log(isP);\n  rl.close();\n});\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        if (n <= 1) { System.out.println(false); return; }\n        boolean isP = true;\n        for (int i = 2; i * i <= n; i++) if (n % i == 0) { isP = false; break; }\n        System.out.println(isP);\n    }\n}\n`,
    },
  },
  {
    slug: 'fibonacci-number-recursive',
    title: 'Fibonacci Number',
    difficulty: 'Easy',
    category: 'Recursion',
    tier: 'free',
    acceptanceRate: 74.0,
    description: 'Calculate the N-th Fibonacci number where `F(0) = 0`, `F(1) = 1`, and `F(n) = F(n-1) + F(n-2)`.',
    constraints: '- `0 <= n <= 30`',
    examples: [{ input: '6', output: '8', orderIndex: 0 }],
    testCases: [
      { input: '6', expectedOutput: '8', isHidden: false, orderIndex: 0 },
      { input: '0', expectedOutput: '0', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      python: `import sys\nn = int(sys.stdin.read().strip())\na, b = 0, 1\nfor _ in range(n): a, b = b, a + b\nprint(a)\n`,
      javascript: `const readline = require('readline');\nconst rl = readline.createInterface({ input: process.stdin });\nrl.on('line', l => {\n  const n = Number(l.trim());\n  let a = 0, b = 1;\n  for (let i = 0; i < n; i++) { [a, b] = [b, a + b]; }\n  console.log(a);\n  rl.close();\n});\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt(), a = 0, b = 1;\n        for (int i = 0; i < n; i++) { int t = a + b; a = b; b = t; }\n        System.out.println(a);\n    }\n}\n`,
    },
  },
];
