/**
 * Step 19: Classic LeetCode Problems — Two Pointers, Hash Table, Backtracking,
 * Math, Sliding Window, and other underrepresented categories.
 */
export const step19Problems = [

  // ── TWO POINTERS ─────────────────────────────────────────────────────────────
  {
    slug: 'two-sum-sorted',
    title: 'Two Sum II - Input Array Is Sorted',
    difficulty: 'Easy',
    category: 'Two Pointers',
    tier: 'free',
    acceptanceRate: 60.5,
    description: 'Given a 1-indexed sorted array `numbers`, find two numbers that add up to `target`. Return their indices (1-indexed). Input: first line is array, second line is target.',
    constraints: '- `2 <= numbers.length <= 3×10^4`\n- `-1000 <= numbers[i] <= 1000`\n- Exactly one solution exists',
    examples: [{ input: '2 7 11 15\n9', output: '1 2', orderIndex: 0 }],
    testCases: [
      { input: '2 7 11 15\n9', expectedOutput: '1 2', isHidden: false, orderIndex: 0 },
      { input: '2 3 4\n6', expectedOutput: '1 3', isHidden: false, orderIndex: 1 },
      { input: '-1 0\n-1', expectedOutput: '1 2', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nlines = sys.stdin.read().split('\\n')\nnums = list(map(int, lines[0].split()))\ntarget = int(lines[1])\nl, r = 0, len(nums)-1\nwhile l < r:\n    s = nums[l] + nums[r]\n    if s == target: print(l+1, r+1); break\n    elif s < target: l += 1\n    else: r -= 1\n`,
      javascript: `const lines = require('fs').readFileSync('/dev/stdin','utf8').split('\\n');\nconst nums = lines[0].split(' ').map(Number), target = Number(lines[1]);\nlet l = 0, r = nums.length-1;\nwhile (l < r) {\n  const s = nums[l]+nums[r];\n  if (s===target) { console.log(l+1, r+1); break; }\n  else if (s<target) l++; else r--;\n}\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int[] nums = Arrays.stream(sc.nextLine().split(\" \")).mapToInt(Integer::parseInt).toArray();\n        int target = sc.nextInt(), l = 0, r = nums.length-1;\n        while (l < r) { int s=nums[l]+nums[r]; if(s==target){System.out.println((l+1)+\" \"+(r+1));return;} else if(s<target)l++; else r--; }\n    }\n}\n`,
    },
  },
  {
    slug: 'three-sum',
    title: '3Sum',
    difficulty: 'Medium',
    category: 'Two Pointers',
    tier: 'mid',
    acceptanceRate: 33.4,
    description: 'Given an integer array `nums`, return all triplets `[nums[i], nums[j], nums[k]]` such that they sum to zero and `i ≠ j ≠ k`. The solution set must not contain duplicate triplets. Each triplet on its own line, space-separated.',
    constraints: '- `3 <= nums.length <= 3000`\n- `-10^5 <= nums[i] <= 10^5`',
    examples: [{ input: '-1 0 1 2 -1 -4', output: '-1 -1 2\n-1 0 1', orderIndex: 0 }],
    testCases: [
      { input: '-1 0 1 2 -1 -4', expectedOutput: '-1 -1 2\n-1 0 1', isHidden: false, orderIndex: 0 },
      { input: '0 1 1', expectedOutput: '', isHidden: false, orderIndex: 1 },
      { input: '0 0 0', expectedOutput: '0 0 0', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nnums = sorted(map(int, sys.stdin.read().split()))\nn, res = len(nums), []\nfor i in range(n-2):\n    if i > 0 and nums[i]==nums[i-1]: continue\n    l, r = i+1, n-1\n    while l < r:\n        s = nums[i]+nums[l]+nums[r]\n        if s==0: res.append((nums[i],nums[l],nums[r])); l+=1; r-=1\n        elif s<0: l+=1\n        else: r-=1\n    while l<r and nums[l]==nums[l-1]: l+=1\n    while l<r and nums[r]==nums[r+1]: r-=1\nprint('\\n'.join(' '.join(map(str,t)) for t in res))\n`,
      javascript: `const nums = require('fs').readFileSync('/dev/stdin','utf8').trim().split(/\\s+/).map(Number).sort((a,b)=>a-b);\nconst res=[];\nfor(let i=0;i<nums.length-2;i++){\n  if(i>0&&nums[i]===nums[i-1])continue;\n  let l=i+1,r=nums.length-1;\n  while(l<r){\n    const s=nums[i]+nums[l]+nums[r];\n    if(s===0){res.push([nums[i],nums[l],nums[r]]);l++;r--;}\n    else if(s<0)l++; else r--;\n    while(l<r&&nums[l]===nums[l-1])l++;\n    while(l<r&&nums[r]===nums[r+1])r--;\n  }\n}\nconsole.log(res.map(t=>t.join(' ')).join('\\n'));\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        int[] nums = Arrays.stream(new Scanner(System.in).nextLine().split(\" \")).mapToInt(Integer::parseInt).toArray();\n        Arrays.sort(nums);\n        List<String> res = new ArrayList<>();\n        for(int i=0;i<nums.length-2;i++){\n            if(i>0&&nums[i]==nums[i-1])continue;\n            int l=i+1,r=nums.length-1;\n            while(l<r){int s=nums[i]+nums[l]+nums[r];if(s==0){res.add(nums[i]+\" \"+nums[l]+\" \"+nums[r]);l++;r--;}else if(s<0)l++;else r--;while(l<r&&nums[l]==nums[l-1])l++;while(l<r&&nums[r]==nums[r+1])r--;}\n        }\n        res.forEach(System.out::println);\n    }\n}\n`,
    },
  },
  {
    slug: 'container-with-most-water',
    title: 'Container With Most Water',
    difficulty: 'Medium',
    category: 'Two Pointers',
    tier: 'mid',
    acceptanceRate: 54.7,
    description: 'Given `n` non-negative integers representing vertical lines on a chart where the width of each line is 1, find two lines that together with the x-axis form a container that holds the most water. Input: a single line of space-separated heights.',
    constraints: '- `n >= 2`\n- `0 <= height[i] <= 10^4`',
    examples: [{ input: '1 8 6 2 5 4 8 3 7', output: '49', orderIndex: 0 }],
    testCases: [
      { input: '1 8 6 2 5 4 8 3 7', expectedOutput: '49', isHidden: false, orderIndex: 0 },
      { input: '1 1', expectedOutput: '1', isHidden: false, orderIndex: 1 },
      { input: '4 3 2 1 4', expectedOutput: '16', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nh = list(map(int, sys.stdin.read().split()))\nl, r, ans = 0, len(h)-1, 0\nwhile l < r:\n    ans = max(ans, min(h[l],h[r])*(r-l))\n    if h[l] < h[r]: l += 1\n    else: r -= 1\nprint(ans)\n`,
      javascript: `const h = require('fs').readFileSync('/dev/stdin','utf8').trim().split(' ').map(Number);\nlet l=0,r=h.length-1,ans=0;\nwhile(l<r){ans=Math.max(ans,Math.min(h[l],h[r])*(r-l));if(h[l]<h[r])l++;else r--;}\nconsole.log(ans);\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        int[] h=Arrays.stream(new Scanner(System.in).nextLine().split(\" \")).mapToInt(Integer::parseInt).toArray();\n        int l=0,r=h.length-1,ans=0;\n        while(l<r){ans=Math.max(ans,Math.min(h[l],h[r])*(r-l));if(h[l]<h[r])l++;else r--;}\n        System.out.println(ans);\n    }\n}\n`,
    },
  },
  {
    slug: 'trapping-rain-water',
    title: 'Trapping Rain Water',
    difficulty: 'Hard',
    category: 'Two Pointers',
    tier: 'pro',
    acceptanceRate: 60.8,
    description: 'Given `n` non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.',
    constraints: '- `n >= 1`\n- `0 <= height[i] <= 10^4`',
    examples: [{ input: '0 1 0 2 1 0 1 3 2 1 2 1', output: '6', orderIndex: 0 }],
    testCases: [
      { input: '0 1 0 2 1 0 1 3 2 1 2 1', expectedOutput: '6', isHidden: false, orderIndex: 0 },
      { input: '4 2 0 3 2 5', expectedOutput: '9', isHidden: false, orderIndex: 1 },
      { input: '3 0 2 0 4', expectedOutput: '7', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nh = list(map(int, sys.stdin.read().split()))\nl, r, lmax, rmax, ans = 0, len(h)-1, 0, 0, 0\nwhile l <= r:\n    if h[l] <= h[r]:\n        if h[l] >= lmax: lmax = h[l]\n        else: ans += lmax - h[l]\n        l += 1\n    else:\n        if h[r] >= rmax: rmax = h[r]\n        else: ans += rmax - h[r]\n        r -= 1\nprint(ans)\n`,
      javascript: `const h=require('fs').readFileSync('/dev/stdin','utf8').trim().split(' ').map(Number);\nlet l=0,r=h.length-1,lmax=0,rmax=0,ans=0;\nwhile(l<=r){if(h[l]<=h[r]){if(h[l]>=lmax)lmax=h[l];else ans+=lmax-h[l];l++;}else{if(h[r]>=rmax)rmax=h[r];else ans+=rmax-h[r];r--;}}\nconsole.log(ans);\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        int[] h=Arrays.stream(new Scanner(System.in).nextLine().split(\" \")).mapToInt(Integer::parseInt).toArray();\n        int l=0,r=h.length-1,lmax=0,rmax=0,ans=0;\n        while(l<=r){if(h[l]<=h[r]){if(h[l]>=lmax)lmax=h[l];else ans+=lmax-h[l];l++;}else{if(h[r]>=rmax)rmax=h[r];else ans+=rmax-h[r];r--;}}\n        System.out.println(ans);\n    }\n}\n`,
    },
  },
  {
    slug: 'sort-colors',
    title: 'Sort Colors (Dutch National Flag)',
    difficulty: 'Medium',
    category: 'Two Pointers',
    tier: 'mid',
    acceptanceRate: 62.2,
    description: 'Given an array `nums` with values 0, 1, and 2, sort it in-place so that all 0s come first, then 1s, then 2s. Use the Dutch National Flag algorithm (one pass). Print the sorted array space-separated.',
    constraints: '- `1 <= n <= 300`\n- `nums[i]` is 0, 1, or 2',
    examples: [{ input: '2 0 2 1 1 0', output: '0 0 1 1 2 2', orderIndex: 0 }],
    testCases: [
      { input: '2 0 2 1 1 0', expectedOutput: '0 0 1 1 2 2', isHidden: false, orderIndex: 0 },
      { input: '2 0 1', expectedOutput: '0 1 2', isHidden: false, orderIndex: 1 },
      { input: '0', expectedOutput: '0', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nnums = list(map(int, sys.stdin.read().split()))\nl, mid, r = 0, 0, len(nums)-1\nwhile mid <= r:\n    if nums[mid]==0: nums[l],nums[mid]=nums[mid],nums[l]; l+=1; mid+=1\n    elif nums[mid]==1: mid+=1\n    else: nums[mid],nums[r]=nums[r],nums[mid]; r-=1\nprint(' '.join(map(str,nums)))\n`,
      javascript: `const nums=require('fs').readFileSync('/dev/stdin','utf8').trim().split(' ').map(Number);\nlet l=0,mid=0,r=nums.length-1;\nwhile(mid<=r){if(nums[mid]===0){[nums[l],nums[mid]]=[nums[mid],nums[l]];l++;mid++;}else if(nums[mid]===1)mid++;else{[nums[mid],nums[r]]=[nums[r],nums[mid]];r--;}}\nconsole.log(nums.join(' '));\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        int[] a=Arrays.stream(new Scanner(System.in).nextLine().split(\" \")).mapToInt(Integer::parseInt).toArray();\n        int l=0,mid=0,r=a.length-1;\n        while(mid<=r){if(a[mid]==0){int t=a[l];a[l]=a[mid];a[mid]=t;l++;mid++;}else if(a[mid]==1)mid++;else{int t=a[mid];a[mid]=a[r];a[r]=t;r--;}}\n        System.out.println(Arrays.stream(a).mapToObj(String::valueOf).reduce((x,y)->x+\" \"+y).get());\n    }\n}\n`,
    },
  },

  // ── HASH TABLE ────────────────────────────────────────────────────────────────
  {
    slug: 'two-sum',
    title: 'Two Sum',
    difficulty: 'Easy',
    category: 'Hash Table',
    tier: 'free',
    acceptanceRate: 52.7,
    description: 'Given an array of integers `nums` and an integer `target`, return the indices of the two numbers that add up to the target. Input: first line is array, second line is target. Output: two 0-indexed indices space-separated.',
    constraints: '- `2 <= nums.length <= 10^4`\n- Exactly one solution\n- Cannot use same element twice',
    examples: [{ input: '2 7 11 15\n9', output: '0 1', orderIndex: 0 }],
    testCases: [
      { input: '2 7 11 15\n9', expectedOutput: '0 1', isHidden: false, orderIndex: 0 },
      { input: '3 2 4\n6', expectedOutput: '1 2', isHidden: false, orderIndex: 1 },
      { input: '3 3\n6', expectedOutput: '0 1', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nlines = sys.stdin.read().split('\\n')\nnums = list(map(int, lines[0].split()))\ntarget = int(lines[1])\nmap_ = {}\nfor i, n in enumerate(nums):\n    if target-n in map_: print(map_[target-n], i); break\n    map_[n] = i\n`,
      javascript: `const lines=require('fs').readFileSync('/dev/stdin','utf8').split('\\n');\nconst nums=lines[0].split(' ').map(Number),target=Number(lines[1]),m=new Map();\nfor(let i=0;i<nums.length;i++){if(m.has(target-nums[i])){console.log(m.get(target-nums[i]),i);break;}m.set(nums[i],i);}\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc=new Scanner(System.in);\n        int[] nums=Arrays.stream(sc.nextLine().split(\" \")).mapToInt(Integer::parseInt).toArray();\n        int target=sc.nextInt();\n        Map<Integer,Integer> map=new HashMap<>();\n        for(int i=0;i<nums.length;i++){if(map.containsKey(target-nums[i])){System.out.println(map.get(target-nums[i])+\" \"+i);return;}map.put(nums[i],i);}\n    }\n}\n`,
    },
  },
  {
    slug: 'group-anagrams',
    title: 'Group Anagrams',
    difficulty: 'Medium',
    category: 'Hash Table',
    tier: 'mid',
    acceptanceRate: 67.4,
    description: 'Given an array of strings `strs`, group the anagrams together. Each line of output contains the anagrams of a group, space-separated, sorted lexicographically within the group. Groups are printed in lexicographic order of the first element.',
    constraints: '- `1 <= strs.length <= 10^4`\n- `0 <= strs[i].length <= 100`\n- Lowercase English letters only',
    examples: [{ input: 'eat tea tan ate nat bat', output: 'ate eat tea\nbat\nant nat tan', orderIndex: 0 }],
    testCases: [
      { input: 'eat tea tan ate nat bat', expectedOutput: 'ate eat tea\nbat\nant nat tan', isHidden: false, orderIndex: 0 },
      { input: 'a', expectedOutput: 'a', isHidden: false, orderIndex: 1 },
      { input: '', expectedOutput: '', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nfrom collections import defaultdict\nwords = sys.stdin.read().split()\ngroups = defaultdict(list)\nfor w in words:\n    groups[tuple(sorted(w))].append(w)\nfor g in sorted(groups.values(), key=lambda x: min(x)):\n    print(' '.join(sorted(g)))\n`,
      javascript: `const words=require('fs').readFileSync('/dev/stdin','utf8').trim().split(' ');\nconst m=new Map();\nfor(const w of words){const k=[...w].sort().join('');m.set(k,(m.get(k)||[]).concat(w));}\nconst groups=[...m.values()].sort((a,b)=>a[0].localeCompare(b[0]));\ngroups.forEach(g=>console.log(g.sort().join(' ')));\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        String[] words=new Scanner(System.in).nextLine().split(\" \");\n        Map<String,List<String>> m=new TreeMap<>();\n        for(String w:words){char[] c=w.toCharArray();Arrays.sort(c);String k=new String(c);m.computeIfAbsent(k,x->new ArrayList<>()).add(w);}\n        m.values().stream().sorted(Comparator.comparing(l->Collections.min(l))).forEach(l->{Collections.sort(l);System.out.println(String.join(\" \",l));});\n    }\n}\n`,
    },
  },
  {
    slug: 'longest-consecutive-sequence',
    title: 'Longest Consecutive Sequence',
    difficulty: 'Medium',
    category: 'Hash Table',
    tier: 'mid',
    acceptanceRate: 46.5,
    description: 'Given an unsorted array of integers, find the length of the longest consecutive elements sequence. Must run in O(n).',
    constraints: '- `0 <= nums.length <= 10^5`\n- `-10^9 <= nums[i] <= 10^9`',
    examples: [{ input: '100 4 200 1 3 2', output: '4', orderIndex: 0 }],
    testCases: [
      { input: '100 4 200 1 3 2', expectedOutput: '4', isHidden: false, orderIndex: 0 },
      { input: '0 3 7 2 5 8 4 6 0 1', expectedOutput: '9', isHidden: false, orderIndex: 1 },
      { input: '', expectedOutput: '0', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nnums = list(map(int, sys.stdin.read().split()))\nif not nums: print(0)\nelse:\n    s = set(nums)\n    best = 0\n    for n in s:\n        if n-1 not in s:\n            cur, streak = n, 1\n            while cur+1 in s: cur+=1; streak+=1\n            best = max(best, streak)\n    print(best)\n`,
      javascript: `const nums=require('fs').readFileSync('/dev/stdin','utf8').trim().split(/\\s+/).filter(Boolean).map(Number);\nif(!nums.length){console.log(0);}else{\nconst s=new Set(nums);let best=0;\nfor(const n of s){if(!s.has(n-1)){let cur=n,streak=1;while(s.has(cur+1)){cur++;streak++;}best=Math.max(best,streak);}}\nconsole.log(best);}\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        String line=new Scanner(System.in).nextLine().trim();\n        if(line.isEmpty()){System.out.println(0);return;}\n        Set<Integer> s=new HashSet<>();\n        for(String x:line.split(\" \"))s.add(Integer.parseInt(x));\n        int best=0;\n        for(int n:s){if(!s.contains(n-1)){int cur=n,streak=1;while(s.contains(cur+1)){cur++;streak++;}best=Math.max(best,streak);}}\n        System.out.println(best);\n    }\n}\n`,
    },
  },
  {
    slug: 'valid-anagram',
    title: 'Valid Anagram',
    difficulty: 'Easy',
    category: 'Hash Table',
    tier: 'free',
    acceptanceRate: 63.3,
    description: 'Given two strings `s` and `t`, return `true` if `t` is an anagram of `s`, and `false` otherwise. Input: two lines, each containing a string.',
    constraints: '- `1 <= s.length, t.length <= 5×10^4`\n- Lowercase English letters only',
    examples: [{ input: 'anagram\nnagaram', output: 'true', orderIndex: 0 }],
    testCases: [
      { input: 'anagram\nnagaram', expectedOutput: 'true', isHidden: false, orderIndex: 0 },
      { input: 'rat\ncar', expectedOutput: 'false', isHidden: false, orderIndex: 1 },
      { input: 'a\nab', expectedOutput: 'false', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nlines = sys.stdin.read().split('\\n')\nprint('true' if sorted(lines[0])==sorted(lines[1]) else 'false')\n`,
      javascript: `const [s,t]=require('fs').readFileSync('/dev/stdin','utf8').split('\\n');\nconsole.log([...s].sort().join()===[...t].sort().join()?'true':'false');\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc=new Scanner(System.in);\n        char[] s=sc.nextLine().toCharArray(), t=sc.nextLine().toCharArray();\n        Arrays.sort(s); Arrays.sort(t);\n        System.out.println(Arrays.equals(s,t)?\"true\":\"false\");\n    }\n}\n`,
    },
  },

  // ── SLIDING WINDOW ────────────────────────────────────────────────────────────
  {
    slug: 'longest-substring-without-repeat',
    title: 'Longest Substring Without Repeating Characters',
    difficulty: 'Medium',
    category: 'Sliding Window',
    tier: 'mid',
    acceptanceRate: 34.3,
    description: 'Given a string `s`, find the length of the longest substring without repeating characters.',
    constraints: '- `0 <= s.length <= 5×10^4`\n- ASCII characters',
    examples: [{ input: 'abcabcbb', output: '3', orderIndex: 0 }],
    testCases: [
      { input: 'abcabcbb', expectedOutput: '3', isHidden: false, orderIndex: 0 },
      { input: 'bbbbb', expectedOutput: '1', isHidden: false, orderIndex: 1 },
      { input: 'pwwkew', expectedOutput: '3', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\ns = sys.stdin.read().strip()\nchar_idx = {}\nl = best = 0\nfor r, c in enumerate(s):\n    if c in char_idx and char_idx[c] >= l:\n        l = char_idx[c]+1\n    char_idx[c] = r\n    best = max(best, r-l+1)\nprint(best)\n`,
      javascript: `const s=require('fs').readFileSync('/dev/stdin','utf8').trim();\nconst m=new Map();\nlet l=0,best=0;\nfor(let r=0;r<s.length;r++){if(m.has(s[r])&&m.get(s[r])>=l)l=m.get(s[r])+1;m.set(s[r],r);best=Math.max(best,r-l+1);}\nconsole.log(best);\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        String s=new Scanner(System.in).nextLine();\n        Map<Character,Integer> m=new HashMap<>();\n        int l=0,best=0;\n        for(int r=0;r<s.length();r++){char c=s.charAt(r);if(m.containsKey(c)&&m.get(c)>=l)l=m.get(c)+1;m.put(c,r);best=Math.max(best,r-l+1);}\n        System.out.println(best);\n    }\n}\n`,
    },
  },
  {
    slug: 'minimum-window-substring',
    title: 'Minimum Window Substring',
    difficulty: 'Hard',
    category: 'Sliding Window',
    tier: 'pro',
    acceptanceRate: 41.5,
    description: 'Given strings `s` and `t`, return the minimum window substring of `s` such that every character in `t` (including duplicates) is included. If none exists, return empty string. Input: two lines — `s` then `t`.',
    constraints: '- `1 <= s.length, t.length <= 10^5`\n- Letters are uppercase and lowercase English',
    examples: [{ input: 'ADOBECODEBANC\nABC', output: 'BANC', orderIndex: 0 }],
    testCases: [
      { input: 'ADOBECODEBANC\nABC', expectedOutput: 'BANC', isHidden: false, orderIndex: 0 },
      { input: 'a\na', expectedOutput: 'a', isHidden: false, orderIndex: 1 },
      { input: 'a\naa', expectedOutput: '', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nfrom collections import Counter\nlines = sys.stdin.read().split('\\n')\ns, t = lines[0], lines[1]\nif not t: print(''); exit()\nneed = Counter(t)\nhave, total = {}, 0\nl, best = 0, ''\nfor r, c in enumerate(s):\n    have[c] = have.get(c,0)+1\n    if c in need and have[c]==need[c]: total+=1\n    while total==len(need):\n        win = s[l:r+1]\n        if not best or len(win)<len(best): best=win\n        lc=s[l]; have[lc]-=1\n        if lc in need and have[lc]<need[lc]: total-=1\n        l+=1\nprint(best)\n`,
      javascript: `const [s,t]=require('fs').readFileSync('/dev/stdin','utf8').split('\\n');\nconst need={}; for(const c of t)need[c]=(need[c]||0)+1;\nconst have={};let total=0,l=0,best='';\nfor(let r=0;r<s.length;r++){const c=s[r];have[c]=(have[c]||0)+1;if(need[c]&&have[c]===need[c])total++;while(total===Object.keys(need).length){const w=s.slice(l,r+1);if(!best||w.length<best.length)best=w;const lc=s[l];have[lc]--;if(need[lc]&&have[lc]<need[lc])total--;l++;}}\nconsole.log(best);\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc=new Scanner(System.in);\n        String s=sc.nextLine(),t=sc.nextLine();\n        int[] need=new int[128],have=new int[128];\n        for(char c:t.toCharArray())need[c]++;\n        int distinct=(int)t.chars().distinct().count(),have_cnt=0,l=0;\n        String best=\"\";\n        for(int r=0;r<s.length();r++){char c=s.charAt(r);have[c]++;if(need[c]>0&&have[c]==need[c])have_cnt++;while(have_cnt==distinct){String w=s.substring(l,r+1);if(best.isEmpty()||w.length()<best.length())best=w;char lc=s.charAt(l);have[lc]--;if(need[lc]>0&&have[lc]<need[lc])have_cnt--;l++;}}\n        System.out.println(best);\n    }\n}\n`,
    },
  },
  {
    slug: 'max-sliding-window',
    title: 'Sliding Window Maximum',
    difficulty: 'Hard',
    category: 'Sliding Window',
    tier: 'pro',
    acceptanceRate: 46.1,
    description: 'Given an array `nums` and a sliding window of size `k`, return an array of the maximum values in each window. Input: first line is the array, second line is `k`.',
    constraints: '- `1 <= nums.length <= 10^5`\n- `-10^4 <= nums[i] <= 10^4`\n- `1 <= k <= nums.length`',
    examples: [{ input: '1 3 -1 -3 5 3 6 7\n3', output: '3 3 5 5 6 7', orderIndex: 0 }],
    testCases: [
      { input: '1 3 -1 -3 5 3 6 7\n3', expectedOutput: '3 3 5 5 6 7', isHidden: false, orderIndex: 0 },
      { input: '1\n1', expectedOutput: '1', isHidden: false, orderIndex: 1 },
      { input: '1 -1\n1', expectedOutput: '1 -1', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nfrom collections import deque\nlines = sys.stdin.read().split('\\n')\nnums = list(map(int, lines[0].split()))\nk = int(lines[1])\ndq, res = deque(), []\nfor i, n in enumerate(nums):\n    while dq and nums[dq[-1]] <= n: dq.pop()\n    dq.append(i)\n    if dq[0] < i-k+1: dq.popleft()\n    if i >= k-1: res.append(nums[dq[0]])\nprint(' '.join(map(str,res)))\n`,
      javascript: `const lines=require('fs').readFileSync('/dev/stdin','utf8').split('\\n');\nconst nums=lines[0].split(' ').map(Number),k=Number(lines[1]);\nconst dq=[],res=[];\nfor(let i=0;i<nums.length;i++){while(dq.length&&nums[dq[dq.length-1]]<=nums[i])dq.pop();dq.push(i);if(dq[0]<i-k+1)dq.shift();if(i>=k-1)res.push(nums[dq[0]]);}\nconsole.log(res.join(' '));\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc=new Scanner(System.in);\n        int[] nums=Arrays.stream(sc.nextLine().split(\" \")).mapToInt(Integer::parseInt).toArray();\n        int k=sc.nextInt();\n        Deque<Integer> dq=new ArrayDeque<>();\n        List<Integer> res=new ArrayList<>();\n        for(int i=0;i<nums.length;i++){while(!dq.isEmpty()&&nums[dq.peekLast()]<=nums[i])dq.pollLast();dq.addLast(i);if(dq.peekFirst()<i-k+1)dq.pollFirst();if(i>=k-1)res.add(nums[dq.peekFirst()]);}\n        System.out.println(res.stream().map(String::valueOf).reduce((a,b)->a+\" \"+b).get());\n    }\n}\n`,
    },
  },
  {
    slug: 'permutation-in-string',
    title: 'Permutation in String',
    difficulty: 'Medium',
    category: 'Sliding Window',
    tier: 'mid',
    acceptanceRate: 44.0,
    description: 'Given two strings `s1` and `s2`, return `true` if `s2` contains a permutation of `s1`, or `false` otherwise. Input: two lines — `s1` then `s2`.',
    constraints: '- `1 <= s1.length, s2.length <= 10^4`\n- Lowercase English letters',
    examples: [{ input: 'ab\neidbaooo', output: 'true', orderIndex: 0 }],
    testCases: [
      { input: 'ab\neidbaooo', expectedOutput: 'true', isHidden: false, orderIndex: 0 },
      { input: 'ab\neidboaoo', expectedOutput: 'false', isHidden: false, orderIndex: 1 },
      { input: 'adc\ndcda', expectedOutput: 'true', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nfrom collections import Counter\nlines = sys.stdin.read().split('\\n')\ns1, s2 = lines[0], lines[1]\nif len(s1)>len(s2): print('false'); exit()\nneed=Counter(s1); have=Counter(s2[:len(s1)])\nif have==need: print('true'); exit()\nfor i in range(len(s1),len(s2)):\n    have[s2[i]]+=1\n    c=s2[i-len(s1)]; have[c]-=1\n    if not have[c]: del have[c]\n    if have==need: print('true'); exit()\nprint('false')\n`,
      javascript: `const [s1,s2]=require('fs').readFileSync('/dev/stdin','utf8').split('\\n');\nconst n=s1.length;\nif(n>s2.length){console.log('false');}else{\nconst need=new Array(26).fill(0),have=new Array(26).fill(0);\nfor(let i=0;i<n;i++){need[s1.charCodeAt(i)-97]++;have[s2.charCodeAt(i)-97]++;}\nconst eq=()=>need.every((v,i)=>v===have[i]);\nif(eq()){console.log('true');}else{\nfor(let i=n;i<s2.length;i++){have[s2.charCodeAt(i)-97]++;have[s2.charCodeAt(i-n)-97]--;if(eq()){console.log('true');process.exit();}}\nconsole.log('false');}}\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc=new Scanner(System.in);\n        String s1=sc.nextLine(),s2=sc.nextLine();\n        int n=s1.length();\n        if(n>s2.length()){System.out.println(\"false\");return;}\n        int[] need=new int[26],have=new int[26];\n        for(char c:s1.toCharArray())need[c-'a']++;\n        for(int i=0;i<n;i++)have[s2.charAt(i)-'a']++;\n        if(Arrays.equals(need,have)){System.out.println(\"true\");return;}\n        for(int i=n;i<s2.length();i++){have[s2.charAt(i)-'a']++;have[s2.charAt(i-n)-'a']--;if(Arrays.equals(need,have)){System.out.println(\"true\");return;}}\n        System.out.println(\"false\");\n    }\n}\n`,
    },
  },

  // ── BACKTRACKING ──────────────────────────────────────────────────────────────
  {
    slug: 'subsets',
    title: 'Subsets',
    difficulty: 'Medium',
    category: 'Backtracking',
    tier: 'mid',
    acceptanceRate: 76.0,
    description: 'Given an integer array `nums` of unique elements, return all possible subsets (the power set). Print each subset on its own line with elements space-separated. Subsets in lexicographic order, empty subset first (empty line).',
    constraints: '- `1 <= nums.length <= 10`\n- `-10 <= nums[i] <= 10`\n- All numbers are unique',
    examples: [{ input: '1 2 3', output: '\n1\n1 2\n1 2 3\n1 3\n2\n2 3\n3', orderIndex: 0 }],
    testCases: [
      { input: '1 2 3', expectedOutput: '\n1\n1 2\n1 2 3\n1 3\n2\n2 3\n3', isHidden: false, orderIndex: 0 },
      { input: '0', expectedOutput: '\n0', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      python: `import sys\nnums = sorted(map(int, sys.stdin.read().split()))\nres = []\ndef bt(start, path):\n    res.append(path[:])\n    for i in range(start, len(nums)):\n        path.append(nums[i])\n        bt(i+1, path)\n        path.pop()\nbt(0, [])\nfor s in sorted(res, key=lambda x: (len(x), x)):\n    print(' '.join(map(str,s)) if s else '')\n`,
      javascript: `const nums=require('fs').readFileSync('/dev/stdin','utf8').trim().split(' ').map(Number).sort((a,b)=>a-b);\nconst res=[];\nfunction bt(start,path){res.push([...path]);for(let i=start;i<nums.length;i++){path.push(nums[i]);bt(i+1,path);path.pop();}}\nbt(0,[]);\nres.sort((a,b)=>a.join()===b.join()?0:a.join()<b.join()?-1:1).forEach(s=>console.log(s.join(' ')));\n`,
      java: `import java.util.*;\npublic class Main {\n    static int[] nums; static List<List<Integer>> res=new ArrayList<>();\n    static void bt(int start,List<Integer> path){res.add(new ArrayList<>(path));for(int i=start;i<nums.length;i++){path.add(nums[i]);bt(i+1,path);path.remove(path.size()-1);}}\n    public static void main(String[] args) {\n        nums=Arrays.stream(new Scanner(System.in).nextLine().split(\" \")).mapToInt(Integer::parseInt).sorted().toArray();\n        bt(0,new ArrayList<>());\n        res.sort(Comparator.comparingInt(List::size));\n        res.forEach(s->System.out.println(s.stream().map(String::valueOf).reduce(\"\",(a,b)->a.isEmpty()?b:a+\" \"+b)));\n    }\n}\n`,
    },
  },
  {
    slug: 'combination-sum',
    title: 'Combination Sum',
    difficulty: 'Medium',
    category: 'Backtracking',
    tier: 'mid',
    acceptanceRate: 71.1,
    description: 'Given an array of distinct integers `candidates` and a `target`, return all unique combinations where the chosen numbers sum to target. Numbers may be used unlimited times. Input: first line is candidates, second line is target. Print each combination sorted, one per line.',
    constraints: '- `1 <= candidates.length <= 30`\n- `2 <= candidates[i] <= 40`\n- `1 <= target <= 40`',
    examples: [{ input: '2 3 6 7\n7', output: '2 2 3\n7', orderIndex: 0 }],
    testCases: [
      { input: '2 3 6 7\n7', expectedOutput: '2 2 3\n7', isHidden: false, orderIndex: 0 },
      { input: '2 3 5\n8', expectedOutput: '2 2 2 2\n2 3 3\n3 5', isHidden: false, orderIndex: 1 },
      { input: '2\n1', expectedOutput: '', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nlines = sys.stdin.read().split('\\n')\ncandidates = sorted(map(int, lines[0].split()))\ntarget = int(lines[1])\nres = []\ndef bt(start, path, remaining):\n    if remaining == 0: res.append(path[:]); return\n    for i in range(start, len(candidates)):\n        if candidates[i] > remaining: break\n        path.append(candidates[i])\n        bt(i, path, remaining-candidates[i])\n        path.pop()\nbt(0, [], target)\nfor c in res: print(' '.join(map(str,c)))\n`,
      javascript: `const lines=require('fs').readFileSync('/dev/stdin','utf8').split('\\n');\nconst cands=lines[0].split(' ').map(Number).sort((a,b)=>a-b),target=Number(lines[1]);\nconst res=[];\nfunction bt(start,path,rem){if(rem===0){res.push([...path]);return;}for(let i=start;i<cands.length;i++){if(cands[i]>rem)break;path.push(cands[i]);bt(i,path,rem-cands[i]);path.pop();}}\nbt(0,[],target);\nres.forEach(c=>console.log(c.join(' ')));\n`,
      java: `import java.util.*;\npublic class Main {\n    static int[] cands; static int target; static List<List<Integer>> res=new ArrayList<>();\n    static void bt(int start,List<Integer> path,int rem){if(rem==0){res.add(new ArrayList<>(path));return;}for(int i=start;i<cands.length;i++){if(cands[i]>rem)break;path.add(cands[i]);bt(i,path,rem-cands[i]);path.remove(path.size()-1);}}\n    public static void main(String[] args) {\n        Scanner sc=new Scanner(System.in);\n        cands=Arrays.stream(sc.nextLine().split(\" \")).mapToInt(Integer::parseInt).sorted().toArray();\n        target=sc.nextInt();\n        bt(0,new ArrayList<>(),target);\n        res.forEach(c->System.out.println(c.stream().map(String::valueOf).reduce((a,b)->a+\" \"+b).orElse(\"\")));\n    }\n}\n`,
    },
  },
  {
    slug: 'permutations',
    title: 'Permutations',
    difficulty: 'Medium',
    category: 'Backtracking',
    tier: 'mid',
    acceptanceRate: 76.3,
    description: 'Given an array `nums` of distinct integers, return all possible permutations. Print each permutation on its own line, space-separated. Print in lexicographic order.',
    constraints: '- `1 <= nums.length <= 6`\n- `-10 <= nums[i] <= 10`\n- All integers are unique',
    examples: [{ input: '1 2 3', output: '1 2 3\n1 3 2\n2 1 3\n2 3 1\n3 1 2\n3 2 1', orderIndex: 0 }],
    testCases: [
      { input: '1 2 3', expectedOutput: '1 2 3\n1 3 2\n2 1 3\n2 3 1\n3 1 2\n3 2 1', isHidden: false, orderIndex: 0 },
      { input: '0 1', expectedOutput: '0 1\n1 0', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      python: `import sys\nfrom itertools import permutations\nnums = sorted(map(int, sys.stdin.read().split()))\nfor p in permutations(nums):\n    print(' '.join(map(str,p)))\n`,
      javascript: `const nums=require('fs').readFileSync('/dev/stdin','utf8').trim().split(' ').map(Number).sort((a,b)=>a-b);\nconst res=[];\nfunction bt(arr,path){if(!arr.length){res.push([...path]);return;}for(let i=0;i<arr.length;i++){path.push(arr[i]);bt([...arr.slice(0,i),...arr.slice(i+1)],path);path.pop();}}\nbt(nums,[]);\nres.forEach(p=>console.log(p.join(' ')));\n`,
      java: `import java.util.*;\npublic class Main {\n    static int[] nums; static List<List<Integer>> res=new ArrayList<>();\n    static void bt(boolean[] used,List<Integer> path){if(path.size()==nums.length){res.add(new ArrayList<>(path));return;}for(int i=0;i<nums.length;i++){if(used[i])continue;used[i]=true;path.add(nums[i]);bt(used,path);path.remove(path.size()-1);used[i]=false;}}\n    public static void main(String[] args) {\n        nums=Arrays.stream(new Scanner(System.in).nextLine().split(\" \")).mapToInt(Integer::parseInt).sorted().toArray();\n        bt(new boolean[nums.length],new ArrayList<>());\n        res.forEach(p->System.out.println(p.stream().map(String::valueOf).reduce((a,b)->a+\" \"+b).get()));\n    }\n}\n`,
    },
  },
  {
    slug: 'word-search',
    title: 'Word Search',
    difficulty: 'Medium',
    category: 'Backtracking',
    tier: 'mid',
    acceptanceRate: 40.8,
    description: 'Given a 2D board of characters and a word, return `true` if the word exists in the grid. The word can be constructed from sequentially adjacent cells (horizontally or vertically). A cell may not be used more than once. Input: first line is `rows cols`, then `rows` lines each with `cols` characters space-separated, then the word.',
    constraints: '- `1 <= m, n <= 6`\n- `1 <= word.length <= 15`\n- Uppercase letters only',
    examples: [{ input: '4 3\nA B C\nA E S\nE E S\n3 1\nABCCED', output: 'true', orderIndex: 0 }],
    testCases: [
      { input: '4 3\nA B C\nA E S\nE E S\n3 1\nABCCED', expectedOutput: 'true', isHidden: false, orderIndex: 0 },
      { input: '3 4\nA B C E\nS F C S\nA D E E\nSEE', expectedOutput: 'true', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      python: `import sys\nlines = sys.stdin.read().split('\\n')\nr,c = map(int, lines[0].split())\nboard = [lines[i+1].split() for i in range(r)]\nword = lines[r+1].strip()\ndef dfs(i,j,k):\n    if k==len(word): return True\n    if not(0<=i<r and 0<=j<c) or board[i][j]!=word[k]: return False\n    tmp=board[i][j]; board[i][j]='#'\n    res=dfs(i+1,j,k+1) or dfs(i-1,j,k+1) or dfs(i,j+1,k+1) or dfs(i,j-1,k+1)\n    board[i][j]=tmp\n    return res\nprint('true' if any(dfs(i,j,0) for i in range(r) for j in range(c)) else 'false')\n`,
      javascript: `const lines=require('fs').readFileSync('/dev/stdin','utf8').split('\\n');\nconst [r,c]=lines[0].split(' ').map(Number);\nconst board=Array.from({length:r},(_,i)=>lines[i+1].split(' '));\nconst word=lines[r+1].trim();\nconst dfs=(i,j,k)=>{if(k===word.length)return true;if(i<0||i>=r||j<0||j>=c||board[i][j]!==word[k])return false;const t=board[i][j];board[i][j]='#';const res=dfs(i+1,j,k+1)||dfs(i-1,j,k+1)||dfs(i,j+1,k+1)||dfs(i,j-1,k+1);board[i][j]=t;return res;};\nconsole.log(Array.from({length:r},(_,i)=>Array.from({length:c},(_,j)=>dfs(i,j,0))).flat().some(Boolean)?'true':'false');\n`,
      java: `import java.util.*;\npublic class Main {\n    static char[][] board; static String word; static int R,C;\n    static boolean dfs(int i,int j,int k){if(k==word.length())return true;if(i<0||i>=R||j<0||j>=C||board[i][j]!=word.charAt(k))return false;char t=board[i][j];board[i][j]='#';boolean res=dfs(i+1,j,k+1)||dfs(i-1,j,k+1)||dfs(i,j+1,k+1)||dfs(i,j-1,k+1);board[i][j]=t;return res;}\n    public static void main(String[] args) {\n        Scanner sc=new Scanner(System.in);R=sc.nextInt();C=sc.nextInt();board=new char[R][C];\n        for(int i=0;i<R;i++)for(int j=0;j<C;j++)board[i][j]=sc.next().charAt(0);\n        word=sc.next();\n        for(int i=0;i<R;i++)for(int j=0;j<C;j++)if(dfs(i,j,0)){System.out.println(\"true\");return;}\n        System.out.println(\"false\");\n    }\n}\n`,
    },
  },

  // ── MATH ─────────────────────────────────────────────────────────────────────
  {
    slug: 'palindrome-number',
    title: 'Palindrome Number',
    difficulty: 'Easy',
    category: 'Math',
    tier: 'free',
    acceptanceRate: 55.6,
    description: 'Given an integer `x`, return `true` if `x` is a palindrome, and `false` otherwise. Negative numbers are not palindromes.',
    constraints: '- `-2^31 <= x <= 2^31 - 1`',
    examples: [{ input: '121', output: 'true', orderIndex: 0 }],
    testCases: [
      { input: '121', expectedOutput: 'true', isHidden: false, orderIndex: 0 },
      { input: '-121', expectedOutput: 'false', isHidden: false, orderIndex: 1 },
      { input: '10', expectedOutput: 'false', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `x = int(input())\nprint('true' if str(x)==str(x)[::-1] and x>=0 else 'false')\n`,
      javascript: `const x=parseInt(require('fs').readFileSync('/dev/stdin','utf8').trim());\nconsole.log(x>=0&&String(x)===String(x).split('').reverse().join('')?'true':'false');\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        long x=new Scanner(System.in).nextLong();\n        String s=String.valueOf(x);\n        System.out.println(x>=0&&s.equals(new StringBuilder(s).reverse().toString())?\"true\":\"false\");\n    }\n}\n`,
    },
  },
  {
    slug: 'reverse-integer',
    title: 'Reverse Integer',
    difficulty: 'Medium',
    category: 'Math',
    tier: 'mid',
    acceptanceRate: 28.4,
    description: 'Given a signed 32-bit integer `x`, return `x` with its digits reversed. If the reversed integer overflows 32-bit signed integer range, return 0.',
    constraints: '- `-2^31 <= x <= 2^31 - 1`',
    examples: [{ input: '123', output: '321', orderIndex: 0 }],
    testCases: [
      { input: '123', expectedOutput: '321', isHidden: false, orderIndex: 0 },
      { input: '-123', expectedOutput: '-321', isHidden: false, orderIndex: 1 },
      { input: '1534236469', expectedOutput: '0', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `x = int(input())\nMAX = 2**31 - 1; MIN = -2**31\nsign = -1 if x < 0 else 1\nrev = int(str(abs(x))[::-1]) * sign\nprint(rev if MIN <= rev <= MAX else 0)\n`,
      javascript: `const x=parseInt(require('fs').readFileSync('/dev/stdin','utf8').trim());\nconst sign=x<0?-1:1,s=String(Math.abs(x)).split('').reverse().join('');\nconst rev=sign*parseInt(s);\nconsole.log(rev>=-2147483648&&rev<=2147483647?rev:0);\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        long x=new Scanner(System.in).nextLong();\n        long sign=x<0?-1:1; String s=String.valueOf(Math.abs(x));\n        long rev=sign*Long.parseLong(new StringBuilder(s).reverse().toString());\n        System.out.println(rev>=-2147483648&&rev<=2147483647?rev:0);\n    }\n}\n`,
    },
  },
  {
    slug: 'power-function',
    title: 'Pow(x, n)',
    difficulty: 'Medium',
    category: 'Math',
    tier: 'mid',
    acceptanceRate: 36.1,
    description: 'Implement `pow(x, n)`, which calculates `x` raised to the power `n`. Input: two lines — `x` (float) and `n` (integer). Print with 5 decimal places.',
    constraints: '- `-100.0 < x < 100.0`\n- `-2^31 <= n <= 2^31 - 1`\n- `n` is an integer, `x != 0` when `n < 0`',
    examples: [{ input: '2.0\n10', output: '1024.00000', orderIndex: 0 }],
    testCases: [
      { input: '2.0\n10', expectedOutput: '1024.00000', isHidden: false, orderIndex: 0 },
      { input: '2.1\n3', expectedOutput: '9.26100', isHidden: false, orderIndex: 1 },
      { input: '2.0\n-2', expectedOutput: '0.25000', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nlines = sys.stdin.read().split('\\n')\nx, n = float(lines[0]), int(lines[1])\nprint(f'{x**n:.5f}')\n`,
      javascript: `const [x,n]=require('fs').readFileSync('/dev/stdin','utf8').split('\\n');\nconsole.log(Math.pow(parseFloat(x),parseInt(n)).toFixed(5));\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc=new Scanner(System.in);\n        double x=sc.nextDouble(); long n=sc.nextLong();\n        System.out.printf(\"%.5f%n\",Math.pow(x,n));\n    }\n}\n`,
    },
  },
  {
    slug: 'count-primes',
    title: 'Count Primes',
    difficulty: 'Medium',
    category: 'Math',
    tier: 'mid',
    acceptanceRate: 33.4,
    description: 'Given an integer `n`, return the number of prime numbers strictly less than `n`.',
    constraints: '- `0 <= n <= 5×10^6`',
    examples: [{ input: '10', output: '4', orderIndex: 0 }],
    testCases: [
      { input: '10', expectedOutput: '4', isHidden: false, orderIndex: 0 },
      { input: '0', expectedOutput: '0', isHidden: false, orderIndex: 1 },
      { input: '1', expectedOutput: '0', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `n = int(input())\nif n < 2: print(0)\nelse:\n    sieve = [True]*(n)\n    sieve[0]=sieve[1]=False\n    for i in range(2,int(n**0.5)+1):\n        if sieve[i]:\n            for j in range(i*i,n,i): sieve[j]=False\n    print(sum(sieve))\n`,
      javascript: `const n=parseInt(require('fs').readFileSync('/dev/stdin','utf8').trim());\nif(n<2){console.log(0);}else{\nconst sieve=new Uint8Array(n).fill(1);\nsieve[0]=sieve[1]=0;\nfor(let i=2;i*i<n;i++)if(sieve[i])for(let j=i*i;j<n;j+=i)sieve[j]=0;\nconsole.log(sieve.reduce((a,b)=>a+b,0));}\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        int n=new Scanner(System.in).nextInt();\n        if(n<2){System.out.println(0);return;}\n        boolean[] sieve=new boolean[n];Arrays.fill(sieve,true);sieve[0]=sieve[1]=false;\n        for(int i=2;(long)i*i<n;i++)if(sieve[i])for(int j=i*i;j<n;j+=i)sieve[j]=false;\n        int cnt=0;for(boolean b:sieve)if(b)cnt++;\n        System.out.println(cnt);\n    }\n}\n`,
    },
  },
  {
    slug: 'happy-number',
    title: 'Happy Number',
    difficulty: 'Easy',
    category: 'Math',
    tier: 'free',
    acceptanceRate: 56.1,
    description: 'A happy number is defined by the following process: Starting with any positive integer, replace the number by the sum of the squares of its digits, and repeat until the number equals 1 (happy) or loops endlessly in a cycle that does not include 1. Return `true` if `n` is a happy number, else `false`.',
    constraints: '- `1 <= n <= 2^31 - 1`',
    examples: [{ input: '19', output: 'true', orderIndex: 0 }],
    testCases: [
      { input: '19', expectedOutput: 'true', isHidden: false, orderIndex: 0 },
      { input: '2', expectedOutput: 'false', isHidden: false, orderIndex: 1 },
      { input: '1', expectedOutput: 'true', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `n = int(input())\ndef sq(x): return sum(int(d)**2 for d in str(x))\nseen = set()\nwhile n != 1 and n not in seen:\n    seen.add(n); n=sq(n)\nprint('true' if n==1 else 'false')\n`,
      javascript: `let n=parseInt(require('fs').readFileSync('/dev/stdin','utf8').trim());\nconst sq=x=>[...String(x)].reduce((a,d)=>a+d*d,0);\nconst seen=new Set();\nwhile(n!==1&&!seen.has(n)){seen.add(n);n=sq(n);}\nconsole.log(n===1?'true':'false');\n`,
      java: `import java.util.*;\npublic class Main {\n    static int sq(int x){int s=0;while(x>0){int d=x%10;s+=d*d;x/=10;}return s;}\n    public static void main(String[] args) {\n        int n=new Scanner(System.in).nextInt();\n        Set<Integer> seen=new HashSet<>();\n        while(n!=1&&!seen.contains(n)){seen.add(n);n=sq(n);}\n        System.out.println(n==1?\"true\":\"false\");\n    }\n}\n`,
    },
  },

  // ── ADDITIONAL CLASSIC ARRAY PROBLEMS ────────────────────────────────────────
  {
    slug: 'product-of-array-except-self',
    title: 'Product of Array Except Self',
    difficulty: 'Medium',
    category: 'Array',
    tier: 'mid',
    acceptanceRate: 65.1,
    description: 'Given an integer array `nums`, return an array `answer` such that `answer[i]` is equal to the product of all elements except `nums[i]`. Must run in O(n) without division. Print space-separated.',
    constraints: '- `2 <= nums.length <= 10^5`\n- `-30 <= nums[i] <= 30`\n- Product of any prefix/suffix fits in 32-bit integer',
    examples: [{ input: '1 2 3 4', output: '24 12 8 6', orderIndex: 0 }],
    testCases: [
      { input: '1 2 3 4', expectedOutput: '24 12 8 6', isHidden: false, orderIndex: 0 },
      { input: '-1 1 0 -3 3', expectedOutput: '0 0 9 0 0', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      python: `import sys\nnums = list(map(int, sys.stdin.read().split()))\nn = len(nums)\nres = [1]*n\nfor i in range(1,n): res[i]=res[i-1]*nums[i-1]\nr = 1\nfor i in range(n-1,-1,-1):\n    res[i]*=r; r*=nums[i]\nprint(' '.join(map(str,res)))\n`,
      javascript: `const nums=require('fs').readFileSync('/dev/stdin','utf8').trim().split(' ').map(Number);\nconst n=nums.length,res=new Array(n).fill(1);\nfor(let i=1;i<n;i++)res[i]=res[i-1]*nums[i-1];\nlet r=1;for(let i=n-1;i>=0;i--){res[i]*=r;r*=nums[i];}\nconsole.log(res.join(' '));\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        int[] nums=Arrays.stream(new Scanner(System.in).nextLine().split(\" \")).mapToInt(Integer::parseInt).toArray();\n        int n=nums.length;int[] res=new int[n];res[0]=1;\n        for(int i=1;i<n;i++)res[i]=res[i-1]*nums[i-1];\n        int r=1;for(int i=n-1;i>=0;i--){res[i]*=r;r*=nums[i];}\n        System.out.println(Arrays.stream(res).mapToObj(String::valueOf).reduce((a,b)->a+\" \"+b).get());\n    }\n}\n`,
    },
  },
  {
    slug: 'find-minimum-rotated-sorted',
    title: 'Find Minimum in Rotated Sorted Array',
    difficulty: 'Medium',
    category: 'Array',
    tier: 'mid',
    acceptanceRate: 48.8,
    description: 'Suppose an array sorted in ascending order is rotated at some pivot. Given the array, find the minimum element. Must be O(log n).',
    constraints: '- `1 <= nums.length <= 5000`\n- `-5000 <= nums[i] <= 5000`\n- All values unique',
    examples: [{ input: '3 4 5 1 2', output: '1', orderIndex: 0 }],
    testCases: [
      { input: '3 4 5 1 2', expectedOutput: '1', isHidden: false, orderIndex: 0 },
      { input: '4 5 6 7 0 1 2', expectedOutput: '0', isHidden: false, orderIndex: 1 },
      { input: '11 13 15 17', expectedOutput: '11', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nnums = list(map(int, sys.stdin.read().split()))\nlo, hi = 0, len(nums)-1\nwhile lo < hi:\n    mid = (lo+hi)//2\n    if nums[mid] > nums[hi]: lo = mid+1\n    else: hi = mid\nprint(nums[lo])\n`,
      javascript: `const nums=require('fs').readFileSync('/dev/stdin','utf8').trim().split(' ').map(Number);\nlet lo=0,hi=nums.length-1;\nwhile(lo<hi){const mid=(lo+hi)>>1;if(nums[mid]>nums[hi])lo=mid+1;else hi=mid;}\nconsole.log(nums[lo]);\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        int[] nums=Arrays.stream(new Scanner(System.in).nextLine().split(\" \")).mapToInt(Integer::parseInt).toArray();\n        int lo=0,hi=nums.length-1;\n        while(lo<hi){int mid=(lo+hi)/2;if(nums[mid]>nums[hi])lo=mid+1;else hi=mid;}\n        System.out.println(nums[lo]);\n    }\n}\n`,
    },
  },
  {
    slug: 'maximum-subarray-kadane',
    title: "Maximum Subarray (Kadane's Algorithm)",
    difficulty: 'Easy',
    category: 'Array',
    tier: 'free',
    acceptanceRate: 50.3,
    description: 'Given an integer array `nums`, find the contiguous subarray with the largest sum and return that sum. Use Kadane\'s Algorithm.',
    constraints: '- `1 <= nums.length <= 10^5`\n- `-10^4 <= nums[i] <= 10^4`',
    examples: [{ input: '-2 1 -3 4 -1 2 1 -5 4', output: '6', orderIndex: 0 }],
    testCases: [
      { input: '-2 1 -3 4 -1 2 1 -5 4', expectedOutput: '6', isHidden: false, orderIndex: 0 },
      { input: '1', expectedOutput: '1', isHidden: false, orderIndex: 1 },
      { input: '5 4 -1 7 8', expectedOutput: '23', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nnums = list(map(int, sys.stdin.read().split()))\ncur = best = nums[0]\nfor n in nums[1:]:\n    cur = max(n, cur+n)\n    best = max(best, cur)\nprint(best)\n`,
      javascript: `const nums=require('fs').readFileSync('/dev/stdin','utf8').trim().split(' ').map(Number);\nlet cur=nums[0],best=nums[0];\nfor(let i=1;i<nums.length;i++){cur=Math.max(nums[i],cur+nums[i]);best=Math.max(best,cur);}\nconsole.log(best);\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        int[] nums=Arrays.stream(new Scanner(System.in).nextLine().split(\" \")).mapToInt(Integer::parseInt).toArray();\n        int cur=nums[0],best=nums[0];\n        for(int i=1;i<nums.length;i++){cur=Math.max(nums[i],cur+nums[i]);best=Math.max(best,cur);}\n        System.out.println(best);\n    }\n}\n`,
    },
  },
  {
    slug: 'jump-game',
    title: 'Jump Game',
    difficulty: 'Medium',
    category: 'Greedy',
    tier: 'mid',
    acceptanceRate: 38.7,
    description: 'Given an integer array `nums` where each element represents the max jump length from that position, return `true` if you can reach the last index from index 0, else `false`.',
    constraints: '- `1 <= nums.length <= 10^4`\n- `0 <= nums[i] <= 10^5`',
    examples: [{ input: '2 3 1 1 4', output: 'true', orderIndex: 0 }],
    testCases: [
      { input: '2 3 1 1 4', expectedOutput: 'true', isHidden: false, orderIndex: 0 },
      { input: '3 2 1 0 4', expectedOutput: 'false', isHidden: false, orderIndex: 1 },
      { input: '0', expectedOutput: 'true', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nnums = list(map(int, sys.stdin.read().split()))\nreach = 0\nfor i, n in enumerate(nums):\n    if i > reach: print('false'); exit()\n    reach = max(reach, i+n)\nprint('true')\n`,
      javascript: `const nums=require('fs').readFileSync('/dev/stdin','utf8').trim().split(' ').map(Number);\nlet reach=0;\nfor(let i=0;i<nums.length;i++){if(i>reach){console.log('false');process.exit();}reach=Math.max(reach,i+nums[i]);}\nconsole.log('true');\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        int[] nums=Arrays.stream(new Scanner(System.in).nextLine().split(\" \")).mapToInt(Integer::parseInt).toArray();\n        int reach=0;\n        for(int i=0;i<nums.length;i++){if(i>reach){System.out.println(\"false\");return;}reach=Math.max(reach,i+nums[i]);}\n        System.out.println(\"true\");\n    }\n}\n`,
    },
  },
  {
    slug: 'merge-intervals',
    title: 'Merge Intervals',
    difficulty: 'Medium',
    category: 'Array',
    tier: 'mid',
    acceptanceRate: 46.4,
    description: 'Given an array of intervals `[start, end]`, merge all overlapping intervals and return the non-overlapping result. Input: each line has two integers `start end`. Output: each merged interval on a new line.',
    constraints: '- `1 <= intervals.length <= 10^4`\n- `0 <= start_i <= end_i <= 10^4`',
    examples: [{ input: '1 3\n2 6\n8 10\n15 18', output: '1 6\n8 10\n15 18', orderIndex: 0 }],
    testCases: [
      { input: '1 3\n2 6\n8 10\n15 18', expectedOutput: '1 6\n8 10\n15 18', isHidden: false, orderIndex: 0 },
      { input: '1 4\n4 5', expectedOutput: '1 5', isHidden: false, orderIndex: 1 },
      { input: '1 4\n0 0', expectedOutput: '0 0\n1 4', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nlines = [l for l in sys.stdin.read().strip().split('\\n') if l.strip()]\nintervals = sorted([list(map(int,l.split())) for l in lines])\nres = [intervals[0]]\nfor s,e in intervals[1:]:\n    if s <= res[-1][1]: res[-1][1]=max(res[-1][1],e)\n    else: res.append([s,e])\nfor a,b in res: print(a,b)\n`,
      javascript: `const lines=require('fs').readFileSync('/dev/stdin','utf8').trim().split('\\n').filter(Boolean);\nconst ivs=lines.map(l=>l.split(' ').map(Number)).sort((a,b)=>a[0]-b[0]);\nconst res=[ivs[0]];\nfor(let i=1;i<ivs.length;i++){const[s,e]=ivs[i];if(s<=res[res.length-1][1])res[res.length-1][1]=Math.max(res[res.length-1][1],e);else res.push([s,e]);}\nres.forEach(([a,b])=>console.log(a,b));\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc=new Scanner(System.in);\n        List<int[]> ivs=new ArrayList<>();\n        while(sc.hasNextInt())ivs.add(new int[]{sc.nextInt(),sc.nextInt()});\n        ivs.sort(Comparator.comparingInt(a->a[0]));\n        List<int[]> res=new ArrayList<>();res.add(ivs.get(0));\n        for(int i=1;i<ivs.size();i++){int[] cur=ivs.get(i),last=res.get(res.size()-1);if(cur[0]<=last[1])last[1]=Math.max(last[1],cur[1]);else res.add(cur);}\n        res.forEach(a->System.out.println(a[0]+\" \"+a[1]));\n    }\n}\n`,
    },
  },
];
