/**
 * Step 5: Strings — Easy / Medium / Hard
 * Tier: Easy → 'free' | Medium → 'mid' | Hard → 'pro'
 */
export const step5Problems = [
  // ── EASY ────────────────────────────────────────────────────────────────────
  {
    slug: 'reverse-a-string',
    title: 'Reverse a String',
    difficulty: 'Easy',
    category: 'String',
    tier: 'free',
    acceptanceRate: 87.0,
    description: 'Given a string `s`, print the string reversed.',
    constraints: '- `1 <= s.length <= 10^5`\n- `s` consists of printable ASCII characters',
    examples: [{ input: 'hello', output: 'olleh', orderIndex: 0 }],
    testCases: [
      { input: 'hello', expectedOutput: 'olleh', isHidden: false, orderIndex: 0 },
      { input: 'abcde', expectedOutput: 'edcba', isHidden: false, orderIndex: 1 },
      { input: 'a', expectedOutput: 'a', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nprint(sys.stdin.read().strip()[::-1])\n`,
      javascript: `const rl = require('readline').createInterface({ input: process.stdin });\nrl.on('line', l => { console.log(l.split('').reverse().join('')); rl.close(); });\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        System.out.println(new StringBuilder(sc.nextLine()).reverse());\n    }\n}\n`,
    },
  },
  {
    slug: 'palindrome-check-string',
    title: 'Check if String is Palindrome',
    difficulty: 'Easy',
    category: 'String',
    tier: 'free',
    acceptanceRate: 83.5,
    description: 'Given a string `s`, return `true` if it reads the same forwards and backwards (case-insensitive, ignoring non-alphanumeric characters), and `false` otherwise.',
    constraints: '- `1 <= s.length <= 2*10^5`\n- `s` may contain letters, digits, and punctuation',
    examples: [{ input: 'A man a plan a canal Panama', output: 'true', orderIndex: 0 }],
    testCases: [
      { input: 'A man a plan a canal Panama', expectedOutput: 'true', isHidden: false, orderIndex: 0 },
      { input: 'race a car', expectedOutput: 'false', isHidden: false, orderIndex: 1 },
      { input: ' ', expectedOutput: 'true', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys, re\ns = re.sub(r'[^a-z0-9]', '', sys.stdin.read().strip().lower())\nprint(str(s == s[::-1]).lower())\n`,
      javascript: `const rl = require('readline').createInterface({ input: process.stdin });\nrl.on('line', l => {\n  const s = l.toLowerCase().replace(/[^a-z0-9]/g,'');\n  console.log(s === s.split('').reverse().join(''));\n  rl.close();\n});\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.nextLine().toLowerCase().replaceAll(\"[^a-z0-9]\",\"\");\n        System.out.println(s.equals(new StringBuilder(s).reverse().toString()));\n    }\n}\n`,
    },
  },
  {
    slug: 'largest-odd-number-string',
    title: 'Largest Odd Number in String',
    difficulty: 'Easy',
    category: 'String',
    tier: 'free',
    acceptanceRate: 76.1,
    description: 'Given a string `num` representing a large integer, return the longest prefix of `num` that represents an odd number. Return empty string if no such prefix exists.',
    constraints: '- `1 <= num.length <= 10^5`\n- `num` consists of digits only, no leading zeros',
    examples: [{ input: '52', output: '5', orderIndex: 0 }],
    testCases: [
      { input: '52', expectedOutput: '5', isHidden: false, orderIndex: 0 },
      { input: '4206', expectedOutput: '', isHidden: false, orderIndex: 1 },
      { input: '35427', expectedOutput: '35427', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\ns = sys.stdin.read().strip()\nfor i in range(len(s)-1, -1, -1):\n    if int(s[i]) % 2 == 1:\n        print(s[:i+1])\n        exit()\nprint('')\n`,
      javascript: `const rl = require('readline').createInterface({ input: process.stdin });\nrl.on('line', l => {\n  const s = l.trim();\n  for (let i = s.length-1; i >= 0; i--) {\n    if (Number(s[i]) % 2 === 1) { console.log(s.slice(0,i+1)); rl.close(); return; }\n  }\n  console.log(''); rl.close();\n});\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        String s = new Scanner(System.in).nextLine().trim();\n        for (int i = s.length()-1; i >= 0; i--) {\n            if ((s.charAt(i)-'0') % 2 == 1) { System.out.println(s.substring(0,i+1)); return; }\n        }\n        System.out.println(\"\");\n    }\n}\n`,
    },
  },
  {
    slug: 'count-vowels-string',
    title: 'Count Vowels in String',
    difficulty: 'Easy',
    category: 'String',
    tier: 'free',
    acceptanceRate: 88.0,
    description: 'Given a string `s`, count the total number of vowels (a, e, i, o, u — case-insensitive) in all substrings of `s`. Return the count modulo 10^9+7.',
    constraints: '- `1 <= s.length <= 10^5`',
    examples: [{ input: 'aba', output: '6', orderIndex: 0 }],
    testCases: [
      { input: 'aba', expectedOutput: '6', isHidden: false, orderIndex: 0 },
      { input: 'abc', expectedOutput: '3', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      python: `import sys\ns = sys.stdin.read().strip()\nMOD = 10**9+7\nn = len(s)\nvowels = set('aeiouAEIOU')\nans = 0\nfor i, c in enumerate(s):\n    if c in vowels:\n        ans = (ans + (i+1)*(n-i)) % MOD\nprint(ans)\n`,
      javascript: `const rl = require('readline').createInterface({ input: process.stdin });\nrl.on('line', l => {\n  const s = l.trim(), n = s.length, MOD = 1000000007n;\n  let ans = 0n;\n  for (let i = 0; i < n; i++) {\n    if ('aeiouAEIOU'.includes(s[i])) ans = (ans + BigInt(i+1)*BigInt(n-i)) % MOD;\n  }\n  console.log(ans.toString()); rl.close();\n});\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        String s = new Scanner(System.in).nextLine().trim();\n        long MOD = 1000000007L, ans = 0, n = s.length();\n        String v = \"aeiouAEIOU\";\n        for (int i = 0; i < n; i++) if (v.indexOf(s.charAt(i)) >= 0) ans = (ans + (long)(i+1)*(n-i)) % MOD;\n        System.out.println(ans);\n    }\n}\n`,
    },
  },
  // ── MEDIUM ────────────────────────────────────────────────────────────────────
  {
    slug: 'longest-substring-no-repeat',
    title: 'Longest Substring Without Repeating Characters',
    difficulty: 'Medium',
    category: 'String',
    tier: 'mid',
    acceptanceRate: 64.8,
    description: 'Given a string `s`, find the length of the longest substring with no repeated characters.',
    constraints: '- `0 <= s.length <= 5*10^4`\n- `s` consists of English letters, digits, symbols, and spaces',
    examples: [{ input: 'abcabcbb', output: '3', orderIndex: 0 }],
    testCases: [
      { input: 'abcabcbb', expectedOutput: '3', isHidden: false, orderIndex: 0 },
      { input: 'bbbbb', expectedOutput: '1', isHidden: false, orderIndex: 1 },
      { input: 'pwwkew', expectedOutput: '3', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\ns = sys.stdin.read().strip()\nseen, lo, best = {}, 0, 0\nfor hi, c in enumerate(s):\n    if c in seen and seen[c] >= lo: lo = seen[c]+1\n    seen[c] = hi\n    best = max(best, hi-lo+1)\nprint(best)\n`,
      javascript: `const rl = require('readline').createInterface({ input: process.stdin });\nrl.on('line', l => {\n  const s = l; const map = new Map();\n  let lo = 0, best = 0;\n  for (let hi = 0; hi < s.length; hi++) {\n    if (map.has(s[hi]) && map.get(s[hi]) >= lo) lo = map.get(s[hi])+1;\n    map.set(s[hi], hi);\n    best = Math.max(best, hi-lo+1);\n  }\n  console.log(best); rl.close();\n});\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        String s = new Scanner(System.in).nextLine();\n        Map<Character,Integer> map = new HashMap<>();\n        int lo = 0, best = 0;\n        for (int hi = 0; hi < s.length(); hi++) {\n            char c = s.charAt(hi);\n            if (map.containsKey(c) && map.get(c) >= lo) lo = map.get(c)+1;\n            map.put(c, hi);\n            best = Math.max(best, hi-lo+1);\n        }\n        System.out.println(best);\n    }\n}\n`,
    },
  },
  {
    slug: 'anagram-groups',
    title: 'Group Anagrams',
    difficulty: 'Medium',
    category: 'String',
    tier: 'mid',
    acceptanceRate: 62.4,
    description: 'Given an array of strings, group the anagrams together. Each group should be printed on one line with elements separated by spaces, and groups sorted lexicographically by the first element. Input: each line is a word.',
    constraints: '- `1 <= strs.length <= 10^4`\n- `0 <= strs[i].length <= 100`\n- Lowercase letters only',
    examples: [{ input: 'eat\ntea\ntan\nate\nnat\nbat', output: 'ate eat tea\nbat\nnat tan', orderIndex: 0 }],
    testCases: [
      { input: 'eat\ntea\ntan\nate\nnat\nbat', expectedOutput: 'ate eat tea\nbat\nnat tan', isHidden: false, orderIndex: 0 },
      { input: 'a', expectedOutput: 'a', isHidden: false, orderIndex: 1 },
    ],
    starterCode: {
      python: `import sys\nfrom collections import defaultdict\nwords = sys.stdin.read().strip().split('\\n')\ngroups = defaultdict(list)\nfor w in words: groups[tuple(sorted(w))].append(w)\nfor g in sorted(groups.values(), key=lambda x: min(x)):\n    print(*sorted(g))\n`,
      javascript: `const lines = require('fs').readFileSync('/dev/stdin','utf8').trim().split('\\n');\nconst map = new Map();\nfor (const w of lines) { const k = w.split('').sort().join(''); if (!map.has(k)) map.set(k,[]); map.get(k).push(w); }\n[...map.values()].sort((a,b)=>Math.min(...a).localeCompare(Math.min(...b))).forEach(g => console.log(g.sort().join(' ')));\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        Map<String,List<String>> m = new TreeMap<>();\n        while (sc.hasNextLine()) {\n            String w = sc.nextLine().trim();\n            if (w.isEmpty()) continue;\n            char[] c = w.toCharArray(); Arrays.sort(c);\n            String k = new String(c);\n            m.computeIfAbsent(k, x -> new ArrayList<>()).add(w);\n        }\n        m.values().stream().sorted(Comparator.comparing(l -> Collections.min(l))).forEach(l -> {\n            Collections.sort(l); System.out.println(String.join(\" \",l));\n        });\n    }\n}\n`,
    },
  },
  // ── HARD ─────────────────────────────────────────────────────────────────────
  {
    slug: 'minimum-window-substring',
    title: 'Minimum Window Substring',
    difficulty: 'Hard',
    category: 'String',
    tier: 'pro',
    acceptanceRate: 43.1,
    description: 'Given strings `s` and `t`, return the minimum window of `s` that contains all characters of `t` (including duplicates). Return empty string if no such window exists. Input: first line is `s`, second line is `t`.',
    constraints: '- `1 <= s.length, t.length <= 10^5`\n- `s` and `t` consist of uppercase and lowercase English letters',
    examples: [{ input: 'ADOBECODEBANC\nABC', output: 'BANC', orderIndex: 0 }],
    testCases: [
      { input: 'ADOBECODEBANC\nABC', expectedOutput: 'BANC', isHidden: false, orderIndex: 0 },
      { input: 'a\na', expectedOutput: 'a', isHidden: false, orderIndex: 1 },
      { input: 'a\nb', expectedOutput: '', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\nfrom collections import Counter\nlines = sys.stdin.read().split('\\n')\ns, t = lines[0], lines[1]\nneed = Counter(t)\nhave, total = {}, 0\nres, resLen = [-1,-1], float('inf')\nl = 0\nfor r, c in enumerate(s):\n    have[c] = have.get(c,0)+1\n    if c in need and have[c] == need[c]: total += 1\n    while total == len(need):\n        if r-l+1 < resLen: resLen = r-l+1; res = [l,r]\n        have[s[l]] -= 1\n        if s[l] in need and have[s[l]] < need[s[l]]: total -= 1\n        l += 1\nprint(s[res[0]:res[1]+1] if resLen != float('inf') else '')\n`,
      javascript: `const lines = require('fs').readFileSync('/dev/stdin','utf8').split('\\n');\nconst s = lines[0], t = lines[1];\nconst need = {}, have = {};\nfor (const c of t) need[c] = (need[c]||0)+1;\nlet total = 0, formed = 0, l = 0, best = '', bestLen = Infinity;\nfor (let r = 0; r < s.length; r++) {\n  const c = s[r]; have[c] = (have[c]||0)+1;\n  if (need[c] && have[c] === need[c]) formed++;\n  while (formed === Object.keys(need).length) {\n    if (r-l+1 < bestLen) { bestLen = r-l+1; best = s.slice(l,r+1); }\n    have[s[l]]--; if (need[s[l]] && have[s[l]] < need[s[l]]) formed--; l++;\n  }\n}\nconsole.log(best);\n`,
      java: `import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.nextLine(), t = sc.nextLine();\n        Map<Character,Integer> need = new HashMap<>(), have = new HashMap<>();\n        for (char c : t.toCharArray()) need.merge(c,1,Integer::sum);\n        int formed = 0, l = 0, bestL = -1, bestR = -1, bestLen = Integer.MAX_VALUE;\n        for (int r = 0; r < s.length(); r++) {\n            char c = s.charAt(r);\n            have.merge(c,1,Integer::sum);\n            if (need.containsKey(c) && have.get(c).equals(need.get(c))) formed++;\n            while (formed == need.size()) {\n                if (r-l+1 < bestLen) { bestLen = r-l+1; bestL = l; bestR = r; }\n                char lc = s.charAt(l); have.merge(lc,-1,Integer::sum);\n                if (need.containsKey(lc) && have.get(lc) < need.get(lc)) formed--;\n                l++;\n            }\n        }\n        System.out.println(bestL == -1 ? \"\" : s.substring(bestL, bestR+1));\n    }\n}\n`,
    },
  },
  {
    slug: 'longest-palindromic-substring',
    title: 'Longest Palindromic Substring',
    difficulty: 'Hard',
    category: 'String',
    tier: 'pro',
    acceptanceRate: 48.7,
    description: 'Given a string `s`, return the longest palindromic substring. If multiple palindromes of the same maximum length exist, return the one that starts earliest.',
    constraints: '- `1 <= s.length <= 1000`\n- `s` consists of digits and English letters',
    examples: [{ input: 'babad', output: 'bab', orderIndex: 0 }],
    testCases: [
      { input: 'babad', expectedOutput: 'bab', isHidden: false, orderIndex: 0 },
      { input: 'cbbd', expectedOutput: 'bb', isHidden: false, orderIndex: 1 },
      { input: 'a', expectedOutput: 'a', isHidden: true, orderIndex: 2 },
    ],
    starterCode: {
      python: `import sys\ns = sys.stdin.read().strip()\ndef expand(l, r):\n    while l >= 0 and r < len(s) and s[l] == s[r]: l -= 1; r += 1\n    return s[l+1:r]\nbest = ''\nfor i in range(len(s)):\n    for p in [expand(i,i), expand(i,i+1)]:\n        if len(p) > len(best): best = p\nprint(best)\n`,
      javascript: `const rl = require('readline').createInterface({ input: process.stdin });\nrl.on('line', l => {\n  const s = l.trim();\n  const exp = (a,b) => { while(a>=0&&b<s.length&&s[a]===s[b]){a--;b++;} return s.slice(a+1,b); };\n  let best = '';\n  for (let i = 0; i < s.length; i++) {\n    [exp(i,i),exp(i,i+1)].forEach(p => { if (p.length > best.length) best = p; });\n  }\n  console.log(best); rl.close();\n});\n`,
      java: `import java.util.*;\npublic class Main {\n    static String s;\n    static String exp(int l, int r) { while(l>=0&&r<s.length()&&s.charAt(l)==s.charAt(r)){l--;r++;} return s.substring(l+1,r); }\n    public static void main(String[] args) {\n        s = new Scanner(System.in).nextLine().trim();\n        String best = \"\";\n        for (int i = 0; i < s.length(); i++) {\n            for (String p : new String[]{exp(i,i),exp(i,i+1)}) if (p.length() > best.length()) best = p;\n        }\n        System.out.println(best);\n    }\n}\n`,
    },
  },
];
